# parallel_code_review.py — AutoGen implementation of parallel_code_review.spl
# Generated by splc (SPL Compiler) — target: Python / AutoGen 0.7.x

import asyncio
import logging
import os
import sys

import openai
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.messages import TextMessage
from autogen_core import CancellationToken
from autogen_ext.models.openai import OpenAIChatCompletionClient

# ── Logging setup ─────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


# ── LLM client factory ────────────────────────────────────────────────────────

def _model_client(model: str, max_tokens: int = 2048) -> OpenAIChatCompletionClient:
    """Build an AutoGen OpenAIChatCompletionClient pointed at the local Ollama endpoint."""
    return OpenAIChatCompletionClient(
        model=model,
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
        api_key="ollama",
        max_tokens=max_tokens,
        model_info={
            "vision": False,
            "function_calling": False,
            "json_output": False,
            "family": "unknown",
        },
    )


async def _single_turn(system: str, user: str, model: str, max_tokens: int = 2048) -> str:
    """
    Issue one LLM call through an AutoGen AssistantAgent and return its reply.
    Used by all sub-workflows and the merge step — keeps agents stateless.
    """
    client = _model_client(model, max_tokens=max_tokens)
    agent = AssistantAgent(
        name="worker",
        system_message=system,
        model_client=client,
    )
    response = await agent.on_messages(
        [TextMessage(content=user, source="user")],
        cancellation_token=CancellationToken(),
    )
    await client.close()
    return response.chat_message.content


# ── SPL: IMPORT '00_style_review' ─────────────────────────────────────────────

async def style_review(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL style_review(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb
    system = (
        f"You are an expert {lang} code style reviewer. "
        "Analyse the code for style issues, readability, naming conventions, "
        "language idioms, and logical correctness. "
        "Output a concise bullet list; label each item CRITICAL, MODERATE, or LOW."
    )
    user = f"Review the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: IMPORT '01_security_audit' ───────────────────────────────────────────

async def security_audit(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL security_audit(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb
    system = (
        f"You are a security engineer specialising in {lang} application security. "
        "Audit the code for vulnerabilities: injection flaws, insecure defaults, "
        "improper error handling, hard-coded secrets, and OWASP Top-10 risks. "
        "Output a concise bullet list; label each item CRITICAL, MODERATE, or LOW."
    )
    user = f"Security-audit the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: IMPORT '02_test_generator' ───────────────────────────────────────────

async def test_generator(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL test_generator(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
    system = (
        f"You are a senior {lang} engineer specialising in test-driven development. "
        "Generate a comprehensive unit-test suite covering happy paths, edge cases, "
        "and error conditions. "
        f"Output only runnable {lang} test code inside a single fenced code block."
    )
    user = f"Generate unit tests for the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: CREATE FUNCTION merge_reviews(style TEXT, sec_audit TEXT, tests TEXT) RETURN TEXT AS $$ … $$ ──

_MERGE_REVIEWS_SYSTEM = (
    "You are a senior engineering lead who writes precise, concise technical reports."
)

_MERGE_REVIEWS_TEMPLATE = """\
You are a senior engineering lead consolidating three independent code-review reports
into a single, actionable plan.

Style & Correctness Review:
{style}

Security Audit:
{sec_audit}

Generated Test Cases:
{tests}

Produce a consolidated report with three sections:
1. **Action Items** — numbered list of changes to make, CRITICAL first, then MODERATE, then LOW
2. **Test Coverage** — paste the generated tests verbatim under a code block
3. **Summary** — one paragraph overall assessment (is this code production-ready?)

Keep the Action Items section under 150 words.\
"""


async def _merge_reviews(
    style: str, sec_audit: str, tests: str, review_model: str
) -> str:
    # SPL: GENERATE merge_reviews(@style_fb, @sec_fb, @test_fb)
    #       WITH OUTPUT BUDGET 1024 TOKENS
    #       USING MODEL @review_model
    #       INTO @report
    user = _MERGE_REVIEWS_TEMPLATE.format(
        style=style, sec_audit=sec_audit, tests=tests
    )
    return await _single_turn(
        _MERGE_REVIEWS_SYSTEM, user, review_model, max_tokens=1024  # OUTPUT BUDGET 1024 TOKENS
    )


# ── SPL: WORKFLOW parallel_code_review ────────────────────────────────────────

async def parallel_code_review(
    code: str,
    lang: str = "python",                                         # SPL INPUT: @lang TEXT DEFAULT 'python'
    review_model: str = "gemma3",                                 # SPL INPUT: @review_model TEXT DEFAULT 'gemma3'
    log_dir: str = "cookbook/63_parallel_code_review/logs-spl",   # SPL INPUT: @log_dir TEXT DEFAULT '...'
) -> str:
    """
    SPL: WORKFLOW parallel_code_review
         OUTPUT: @report TEXT
    """
    report: str = ""  # SPL: OUTPUT @report TEXT

    os.makedirs(log_dir, exist_ok=True)

    try:
        # SPL: LOGGING f'[parallel_code_review] starting 3-way parallel review | lang={@lang} ...' LEVEL INFO
        log.info(
            "[parallel_code_review] starting 3-way parallel review | "
            "lang=%s review_model=%s log_dir=%s",
            lang, review_model, log_dir,
        )

        # SPL: CALL PARALLEL
        #   style_review   (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb,
        #   security_audit (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb,
        #   test_generator (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
        # END
        style_fb, sec_fb, test_fb = await asyncio.gather(
            style_review(code, lang=lang, review_model=review_model, log_dir=log_dir),
            security_audit(code, lang=lang, review_model=review_model, log_dir=log_dir),
            test_generator(code, lang=lang, review_model=review_model, log_dir=log_dir),
        )

        # Write individual sub-review outputs to log_dir
        for filename, content in [
            ("style_review.md", style_fb),
            ("security_audit.md", sec_fb),
            ("test_generator.md", test_fb),
        ]:
            with open(os.path.join(log_dir, filename), "w", encoding="utf-8") as fh:
                fh.write(content)

        # SPL: LOGGING '[parallel_code_review] parallel checks complete — merging into report' LEVEL INFO
        log.info("[parallel_code_review] parallel checks complete — merging into report")

        report = await _merge_reviews(
            style=style_fb,
            sec_audit=sec_fb,
            tests=test_fb,
            review_model=review_model,
        )

        with open(os.path.join(log_dir, "report.md"), "w", encoding="utf-8") as fh:
            fh.write(report)

        # SPL: LOGGING f'[parallel_code_review] done | report_len={len(@report)}' LEVEL INFO
        log.info("[parallel_code_review] done | report_len=%d", len(report))

        # SPL: COMMIT @report
        return report

    # SPL: EXCEPTION WHEN ModelUnavailable THEN
    except (openai.APIConnectionError, openai.AuthenticationError) as exc:
        # SPL: LOGGING f'[parallel_code_review] model unavailable: {@review_model}' LEVEL ERROR
        log.error(
            "[parallel_code_review] model unavailable: %s — %s", review_model, exc
        )
        # SPL: RETURN '[ERROR] Model unavailable.' WITH status = 'failed'
        return "[ERROR] Model unavailable."

    # SPL: EXCEPTION WHEN BudgetExceeded THEN
    except openai.BadRequestError as exc:
        if "context" not in str(exc).lower() and "token" not in str(exc).lower():
            raise
        # SPL: LOGGING '[parallel_code_review] token budget exceeded during merge' LEVEL WARN
        log.warning("[parallel_code_review] token budget exceeded during merge")
        # SPL: COMMIT @report WITH status = 'truncated'
        return report  # return whatever was accumulated before truncation


# ── CLI entry point ───────────────────────────────────────────────────────────

import click

@click.command()
@click.option("--code", required=True, help="Source code to review, or a file path to read from")
@click.option("--lang", default="python", show_default=True, help="Programming language")
@click.option("--review-model", default="gemma3", show_default=True, help="LLM model name served by Ollama")
@click.option("--log-dir", default="cookbook/63_parallel_code_review/logs-spl", show_default=True, help="Log directory (kept for SPL INPUT parity)")
@click.option("--report", default="review.md", show_default=True, help="Output file for the review report")
def main(code: str, lang: str, review_model: str, log_dir: str, report: str):
    """Parallel Code Review — AutoGen implementation of parallel_code_review.spl"""
    # If --code looks like an existing file, read its contents
    if os.path.isfile(code):
        with open(code, "r", encoding="utf-8") as fh:
            code = fh.read()

    result = asyncio.run(
        parallel_code_review(
            code=code,
            lang=lang,
            review_model=review_model,
            log_dir=log_dir,
        )
    )
    print(result)
    with open(report, "w", encoding="utf-8") as fh:
        fh.write(result)
    log.info("report written to %s", report)


if __name__ == "__main__":
    main()