"""
rag_e2e — generated by splc (deterministic Python/PocketFlow transpiler)

PocketFlow pattern: prep(shared) → exec(prep_res) → post(shared, prep_res, exec_res)
                    Extract       → Transform        → Load
                    (ETL applied to LLM orchestration)

Pattern: step1 → step2 → ... → output

Usage:
    pip install pocketflow click
    python rag_e2e_python_pocketflow.py --task "Your task here"
"""

from pathlib import Path

import click
from pocketflow import Flow, Node

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

CHUNK_DOCUMENTS_PROMPT = """\
  Split the following raw texts into fixed-size segments of approximately 200 tokens each.
  Return each segment as a separate item in a list.
  Texts: {texts}"""

EMBED_DOCUMENTS_PROMPT = """\
  For each chunk in the provided list, produce a dense vector embedding using the OpenAI
  text-embedding-ada-002 model. Return the full embedding matrix as a list of vectors.
  Chunks: {chunks}"""

CREATE_INDEX_PROMPT = """\
  Construct a FAISS flat-L2 vector index from the provided embedding matrix.
  Return the serialised index structure as a JSON object.
  Embeddings: {embeddings}"""

EMBED_QUERY_PROMPT = """\
  Produce a dense vector embedding for the following query using the OpenAI
  text-embedding-ada-002 model. Return the embedding as a vector.
  Query: {query}"""

RETRIEVE_DOCUMENT_PROMPT = """\
  Perform a nearest-neighbour search (k=1) against the FAISS flat-L2 index using the
  provided query embedding. Return the single best-matching chunk from the chunks list.
  Index: {index}
  Query embedding: {query_embedding}
  Chunks: {chunks}"""

GENERATE_ANSWER_PROMPT = """\
  You are a helpful assistant. Answer the user''s question using ONLY the context provided.
  Do not introduce information not present in the context.

  Context:
  {retrieved_document}

  Question:
  {query}

  Answer:"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _call_llm(model: str, prompt: str) -> str:
    """Call the LLM via Ollama REST API. Replace with your preferred adapter."""
    import urllib.request, json
    payload = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["response"].strip()


def _write(path: str, content: str) -> None:
    """Write content to a file, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ── Nodes  (each mirrors one GENERATE / CALL statement) ────────────────────

class Step1_Rag_indexNode(Node):
    # SPL: CALL rag_index(...) INTO @index

    def prep(self, shared):
        # Extract — pull required vars from shared store
        texts = shared["texts"]
        return texts

    def exec(self, prep_res):
        # Transform — sub-workflow call: rag_index
        # NOTE: In standalone mode this calls the LLM to simulate rag_index.
        # For production, replace with a direct function call.
        texts = prep_res
        print("Calling rag_index ...")
        return _call_llm("llama3.2", f"Execute rag_index: {texts}")

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["index"] = exec_res
        return "step2"

class Step2_Chunk_documentsNode(Node):
    # SPL: GENERATE chunk_documents(...) INTO @chunks

    def prep(self, shared):
        # Extract — pull required vars from shared store
        texts = shared["texts"]
        return texts

    def exec(self, prep_res):
        # Transform — LLM call: chunk_documents
        texts = prep_res
        print("Running chunk_documents ...")
        return _call_llm("llama3.2", CHUNK_DOCUMENTS_PROMPT.format(texts=texts))

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["chunks"] = exec_res
        return "step3"

class Step3_Rag_queryNode(Node):
    # SPL: CALL rag_query(...) INTO @answer

    def prep(self, shared):
        # Extract — pull required vars from shared store
        query = shared["query"]
        index = shared["index"]
        chunks = shared["chunks"]
        return query, index, chunks

    def exec(self, prep_res):
        # Transform — sub-workflow call: rag_query
        # NOTE: In standalone mode this calls the LLM to simulate rag_query.
        # For production, replace with a direct function call.
        query, index, chunks = prep_res
        print("Calling rag_query ...")
        return _call_llm("llama3.2", f"Execute rag_query: {query}")

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["answer"] = exec_res
        shared["status"] = "complete"
        print(f"\nStatus:  complete")
        print(f"\n{shared.get('answer', exec_res)}")
        return None

# ── Flow wiring  (mirrors WORKFLOW control flow) ─────────────────────────────
# SPL: sequential GENERATE/CALL chain — linear pipeline

def build_flow() -> Flow:
    step1 = Step1_Rag_indexNode()
    step2 = Step2_Chunk_documentsNode()
    step3 = Step3_Rag_queryNode()

    step1 - "step2" >> step2
    step2 - "step3" >> step3
    return Flow(start=step1)

# ── Entry point  (SPL: built into CLI — `spl3 run ...`) ────────────────────────

@click.command()
@click.option("--texts", required=True)
@click.option("--query", required=True)
def main(texts: str, query: str):
    # SPL: INPUT @vars → shared store (ETL staging area)
    shared = {
        "texts": texts,
        "query": query,
    }
    build_flow().run(shared)


if __name__ == "__main__":
    main()