"""splc — deterministic SPL 3.0 → python/linalg .ipynb transpiler.

No LLM required.  Converts a .spl logical view to an annotated Jupyter notebook
where each SPL statement becomes one or more executable cells.

Output is a valid .ipynb (nbformat 4) ready to run with:
    jupyter nbconvert --to notebook --execute <output>.ipynb

Construct mapping (SPL → notebook cell):
  WORKFLOW … DO … END     → markdown header + setup code cell
  CREATE FUNCTION         → prompt constant hoisted into setup cell
  GENERATE fn(…) INTO @v  → code cell calling _llm_call(prompt)
  CALL proc(…) INTO @v    → code cell calling the Python function
  SOLVE @v TYPE := expr   → code cell: v = expr  (@@var@@ → var)
  ASSERT expr             → code cell: assert bool(expr) with OTHERWISE handler
  EVALUATE @v WHEN …      → code cell: if/elif/else
  WHILE cond DO           → code cell: while loop
  @v := expr              → code cell: v = expr
  COMMIT @v               → code cell: write output + print
  LOGGING msg             → code cell: print(msg)

DODA principle:
  The .spl file is the logical view; this notebook is the physical artifact for
  the python/linalg domain target.  Changing domain = swap linalg_graph.py.
"""

from __future__ import annotations

import json
import re
import textwrap
from typing import Any

from spl.ast_nodes import (
    AssignmentStatement,
    BinaryOp,
    CallStatement,
    CommitStatement,
    CompoundCondition,
    CreateFunctionStatement,
    EvaluateStatement,
    FStringLiteral,
    GenerateIntoStatement,
    Literal,
    LoggingStatement,
    NamedArg,
    ParamRef,
    SemanticCondition,
    WhileStatement,
    WorkflowStatement,
)
from spl3.ast_nodes import (
    AssertStatement,
    NoneLiteral,
    SolveStatement,
    UnaryOp,
)


# ---------------------------------------------------------------------------
# Notebook format helpers
# ---------------------------------------------------------------------------

def _code_cell(source: str, metadata: dict | None = None) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": metadata or {},
        "outputs": [],
        "source": _source_lines(source),
    }


def _markdown_cell(source: str, metadata: dict | None = None) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": metadata or {},
        "source": _source_lines(source),
    }


def _source_lines(text: str) -> list[str]:
    """Split source into a list of lines (each ending with \\n, last without)."""
    lines = text.rstrip("\n").split("\n")
    return [ln + "\n" for ln in lines[:-1]] + [lines[-1]]


def _notebook(cells: list[dict]) -> dict[str, Any]:
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
            "splc": {
                "target": "python/linalg",
                "domain_library": "linalg_graph.py",
            },
        },
        "cells": cells,
    }


# ---------------------------------------------------------------------------
# Transpiler
# ---------------------------------------------------------------------------

_SETUP_TEMPLATE = """\
# ── python/linalg target setup — generated by splc ───────────────────────────
import sys, os, json
from pathlib import Path

# Locate linalg_graph.py (cookbook/65_linalg_micro_textbook or current dir)
_SEARCH = [
    Path(__file__).parent if "__file__" in dir() else Path("."),
    Path(os.environ.get("LINALG_GRAPH_DIR", ".")),
    Path("."),
]
for _p in _SEARCH:
    _p = _p.resolve()
    if (_p / "linalg_graph.py").exists():
        sys.path.insert(0, str(_p))
        break
import linalg_graph as lg
from linalg_graph import (
    build, acyclic, reducible, minimal, ancestors, restrict,
    productivity_order, in_graph, applications_of, new_primitives,
    first_radical_primitives, both_radical_primitives,
    concept_names, primitive_names,
)

# ── LLM helper (configure SPL_MODEL or replace with your adapter) ────────────
def _llm_call(prompt: str, model: str | None = None) -> str:
    import subprocess
    _m = model or os.environ.get("SPL_MODEL", "llama3.2")
    r = subprocess.run(["ollama", "run", _m], input=prompt,
                       capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        raise RuntimeError(f"LLM call failed: {r.stderr}")
    return r.stdout.strip()

# ── Math verifier helpers ─────────────────────────────────────────────────────
def _verify_math(section: str) -> str:
    \"\"\"Returns 'pass' or a description of the failure.\"\"\"
    try:
        import sympy  # noqa: F401 — presence check
        return "pass"   # TODO: parse worked examples from section and recompute
    except Exception as exc:
        return f"fail: {exc}"

def _shape_check(section: str) -> str:
    \"\"\"Check matrix dimension compatibility. Returns 'pass' or error.\"\"\"
    return "pass"  # TODO: parse matrix expressions and check shapes

# ── Workflow parameters (override before running or use papermill) ────────────
{param_defaults}
"""

_HEADER_TEMPLATE = """\
# {name}

**Generated by** `splc --lang python/linalg`
**Domain library:** `linalg_graph.py`
**DODA note:** The source `.spl` file is the logical view; this notebook is the physical artifact for the `python/linalg` domain target.

## Inputs

{input_table}
"""


class LinalgTranspiler:
    """Deterministic SPL 3.0 → python/linalg .ipynb transpiler.

    Usage::

        from spl.lexer import Lexer
        from spl3.parser import SPL3Parser
        from spl3.splc.transpiler_linalg import LinalgTranspiler
        from pathlib import Path

        tokens = Lexer(src).tokenize()
        program = SPL3Parser(tokens).parse()
        nb_json = LinalgTranspiler("build_micro_textbook", spl_dir=Path(".")).transpile(program)
        Path("out.ipynb").write_text(nb_json)
    """

    def __init__(self, recipe_name: str, spl_dir=None):
        self.recipe_name = recipe_name
        self.spl_dir = spl_dir
        self.prompts: dict[str, str] = {}
        self.fn_params: dict[str, list] = {}

    # ── Public entry point ────────────────────────────────────────────────────

    def transpile(self, program) -> str:
        """Return .ipynb JSON string."""
        # Pass 1: collect CREATE FUNCTION definitions
        for stmt in program.statements:
            if isinstance(stmt, CreateFunctionStatement):
                self.prompts[stmt.name] = stmt.body
                self.fn_params[stmt.name] = stmt.parameters

        # Find the main workflow
        workflows = [s for s in program.statements if isinstance(s, WorkflowStatement)]
        if not workflows:
            raise ValueError("No WORKFLOW statement found in SPL source")
        main_wf = workflows[-1]

        cells: list[dict] = []
        cells.append(self._header_cell(main_wf))
        cells.append(self._setup_cell(main_wf))
        if self.prompts:
            cells.append(self._prompts_cell())

        for stmt in main_wf.body:
            cells.extend(self._stmt_to_cells(stmt))

        return json.dumps(_notebook(cells), indent=2, ensure_ascii=False)

    # ── Cell builders ─────────────────────────────────────────────────────────

    def _header_cell(self, wf: WorkflowStatement) -> dict:
        rows = ["| Parameter | Type | Description |", "|-----------|------|-------------|"]
        for p in wf.inputs:
            rows.append(f"| `@{p.name}` | `{p.param_type or 'TEXT'}` | — |")
        table = "\n".join(rows) if wf.inputs else "_No inputs declared._"
        src = _HEADER_TEMPLATE.format(name=wf.name.replace("_", " ").title(), input_table=table)
        return _markdown_cell(src)

    def _setup_cell(self, wf: WorkflowStatement) -> dict:
        param_lines: list[str] = []
        for p in wf.inputs:
            typ = (p.param_type or "TEXT").upper()
            if typ in ("INT", "INTEGER"):
                default = "1"
            elif typ in ("FLOAT", "NUMBER"):
                default = "1.0"
            elif typ in ("SET", "LIST"):
                default = "[]"
            else:
                default = f'"{p.name.lower()}"'
            param_lines.append(f"{p.name} = {default}  # {typ}")
        # Initialise OUTPUT variables
        for p in wf.outputs:
            typ = (p.param_type or "TEXT").upper()
            if typ in ("LIST", "SET"):
                param_lines.append(f"{p.name} = []")
            elif typ in ("INT", "INTEGER"):
                param_lines.append(f"{p.name} = 0")
            elif typ in ("FLOAT", "NUMBER"):
                param_lines.append(f"{p.name} = 0.0")
            else:
                param_lines.append(f'{p.name} = ""')

        # Build the concept graph once in setup
        param_lines.append("")
        param_lines.append("# Pre-build the linalg concept graph (reused by all SOLVE/ASSERT cells)")
        param_lines.append("graph = lg.build()")
        param_lines.append("primitives = lg.both_radical_primitives()")
        param_lines.append(
            'print(f"linalg_graph loaded: {graph.number_of_nodes()} nodes, '
            '{graph.number_of_edges()} edges")'
        )

        src = _SETUP_TEMPLATE.replace("{param_defaults}", "\n".join(param_lines))
        return _code_cell(src)

    def _prompts_cell(self) -> dict:
        lines = ["# ── Prompt templates (mirrors CREATE FUNCTION blocks in .spl) ────────────"]
        for name, body in self.prompts.items():
            const = name.upper() + "_PROMPT"
            body_clean = textwrap.dedent(body).strip("\n")
            lines.append(f'\n{const} = """\\\n{body_clean}\n"""')
        return _code_cell("\n".join(lines))

    # ── Statement dispatcher ──────────────────────────────────────────────────

    def _stmt_to_cells(self, stmt) -> list[dict]:
        if isinstance(stmt, SolveStatement):
            return [self._solve_cell(stmt)]
        if isinstance(stmt, AssertStatement):
            return [self._assert_cell(stmt)]
        if isinstance(stmt, GenerateIntoStatement):
            return [self._generate_cell(stmt)]
        if isinstance(stmt, CallStatement):
            return [self._call_cell(stmt)]
        if isinstance(stmt, AssignmentStatement):
            return [self._assignment_cell(stmt)]
        if isinstance(stmt, EvaluateStatement):
            return [self._evaluate_cell(stmt)]
        if isinstance(stmt, WhileStatement):
            return [self._while_cell(stmt)]
        if isinstance(stmt, CommitStatement):
            return [self._commit_cell(stmt)]
        if isinstance(stmt, LoggingStatement):
            return [self._logging_cell(stmt)]
        # Unsupported — emit a comment cell
        type_name = type(stmt).__name__
        return [_code_cell(f"# TODO: {type_name} not yet emitted by python/linalg transpiler")]

    # ── Per-construct cell emitters ───────────────────────────────────────────

    def _solve_cell(self, stmt: SolveStatement) -> dict:
        expr = _subst_markers(stmt.python_template)
        typ = f" {stmt.target_type}" if stmt.target_type else ""
        spl_display = _markers_to_at(stmt.python_template)
        spl_comment = f"# SPL: SOLVE @{stmt.target_variable}{typ} := {spl_display}"
        code = (
            f"{spl_comment}\n"
            f"{stmt.target_variable} = {expr}\n"
            f"print(f'@{stmt.target_variable} =', {stmt.target_variable})"
        )
        return _code_cell(code, metadata={"tags": ["solve"]})

    def _assert_cell(self, stmt: AssertStatement) -> dict:
        expr = _subst_markers(stmt.python_template)
        spl_comment = f"# SPL: ASSERT {_markers_to_at(stmt.python_template)}"
        lines = [spl_comment, f"_assert_result = bool({expr})"]
        if stmt.otherwise_body:
            otherwise_lines = self._body_to_python(stmt.otherwise_body, indent="    ")
            lines += [
                "if not _assert_result:",
                f'    print(f"ASSERT failed: {expr!r} → executing OTHERWISE")',
            ]
            lines.extend(otherwise_lines)
            lines += [
                "else:",
                f'    print(f"✓ ASSERT {expr}")',
            ]
        else:
            lines += [
                "if not _assert_result:",
                f'    raise AssertionError(f"ASSERT failed: {expr!r}")',
                "else:",
                f'    print(f"✓ ASSERT {expr}")',
            ]
        return _code_cell("\n".join(lines), metadata={"tags": ["assert"]})

    def _generate_cell(self, stmt: GenerateIntoStatement) -> dict:
        gc = stmt.generate_clause
        fn = gc.function_name
        args_spl = [self._spl_arg(a) for a in gc.arguments]
        var = stmt.target_variable

        prompt_const = fn.upper() + "_PROMPT"
        if fn in self.prompts:
            parts: list[str] = []
            for a in gc.arguments:
                if isinstance(a, ParamRef):
                    parts.append(f"{self._key(a.name)}={self._expr_py(a)}")
                elif isinstance(a, NamedArg):
                    parts.append(f"{a.name}={self._expr_py(a.value)}")
                else:
                    parts.append(self._expr_py(a))
            fmt_args = ", ".join(parts)
            prompt_expr = f"{prompt_const}.format({fmt_args})" if fmt_args else prompt_const
        else:
            prompt_expr = (
                f'"GENERATE {fn}({", ".join(args_spl)})"  '
                f"# ← replace with actual prompt for {fn}"
            )

        spl_comment = f"# SPL: GENERATE {fn}({', '.join(args_spl)}) INTO @{var}"
        code = (
            f"{spl_comment}\n"
            f"_prompt = {prompt_expr}\n"
            f"{var} = _llm_call(_prompt)\n"
            f"print(f'@{var}:', {var}[:200] if isinstance({var}, str) else {var})"
        )
        return _code_cell(code, metadata={"tags": ["generate"]})

    def _call_cell(self, stmt: CallStatement) -> dict:
        fn = stmt.procedure_name
        args_spl = [self._spl_arg(a) for a in stmt.arguments]
        args_py  = [self._expr_py(a) for a in stmt.arguments]

        spl_comment = f"# SPL: CALL {fn}({', '.join(args_spl)})"
        if stmt.target_variable:
            spl_comment += f" INTO @{stmt.target_variable}"

        # Well-known helpers
        if fn == "verify_math":
            py_call = f"_verify_math({', '.join(args_py)})"
        elif fn == "shape_check":
            py_call = f"_shape_check({', '.join(args_py)})"
        elif fn == "run_python":
            # CALL run_python('code') INTO @var — emit the Python code as a cell
            code_arg = args_py[0] if args_py else '""'
            py_call = f"eval(compile({code_arg}, '<spl_run_python>', 'exec'))"
        else:
            py_call = f"{fn}({', '.join(args_py)})"

        result_var = stmt.target_variable or "_result"
        code = (
            f"{spl_comment}\n"
            f"{result_var} = {py_call}\n"
            f"print(f'@{result_var}:', {result_var})"
        )
        return _code_cell(code, metadata={"tags": ["call"]})

    def _assignment_cell(self, stmt: AssignmentStatement) -> dict:
        var = self._key(stmt.variable)
        expr = self._expr_py(stmt.expression)
        spl_comment = f"# SPL: @{var} := {self._spl_expr(stmt.expression)}"
        code = f"{spl_comment}\n{var} = {expr}\nprint(f'@{var} =', {var})"
        return _code_cell(code)

    def _evaluate_cell(self, stmt: EvaluateStatement) -> dict:
        var = self._expr_py(stmt.expression)
        lines = [f"# SPL: EVALUATE {self._spl_expr(stmt.expression)}"]
        for i, wc in enumerate(stmt.when_clauses):
            kw = "if" if i == 0 else "elif"
            cond_str = self._render_when_condition(wc.condition, var)
            lines.append(f"{kw} {cond_str}:")
            inner = self._body_to_python(wc.statements, indent="    ")
            if inner:
                lines.extend(inner)
            else:
                lines.append("    pass")
        if stmt.else_statements:
            lines.append("else:")
            inner = self._body_to_python(stmt.else_statements, indent="    ")
            lines.extend(inner if inner else ["    pass"])
        return _code_cell("\n".join(lines), metadata={"tags": ["evaluate"]})

    def _while_cell(self, stmt: WhileStatement) -> dict:
        cond = self._render_condition(stmt.condition)
        max_iter = stmt.max_iterations or 10
        lines = [
            f"# SPL: WHILE {self._spl_condition(stmt.condition)} DO",
            f"_while_iter = 0",
            f"while ({cond}) and _while_iter < {max_iter}:",
            f"    _while_iter += 1",
        ]
        inner = self._body_to_python(stmt.body, indent="    ")
        lines.extend(inner if inner else ["    pass"])
        lines.append(f"# END WHILE  (ran {{_while_iter}} iteration(s))")
        return _code_cell("\n".join(lines), metadata={"tags": ["while"]})

    def _commit_cell(self, stmt: CommitStatement) -> dict:
        var = self._expr_py(stmt.expression)
        status_parts = ", ".join(
            f"{k}={self._expr_py(v)}" for k, v in (stmt.options or {}).items()
        )
        spl_src = f"COMMIT {self._spl_expr(stmt.expression)}"
        if status_parts:
            spl_src += f" WITH {status_parts}"
        lines = [
            f"# SPL: {spl_src}",
            f"import json",
            f"_output = {var}",
            f'_result_path = Path("{self.recipe_name}_output.json")',
            f"_result_path.write_text(json.dumps(_output, indent=2, default=str))",
            f'print(f"Committed to {{_result_path}}")',
        ]
        if status_parts:
            lines.append(f"# status: {status_parts}")
        return _code_cell("\n".join(lines), metadata={"tags": ["commit"]})

    def _logging_cell(self, stmt: LoggingStatement) -> dict:
        msg = self._expr_py(stmt.expression)
        level = stmt.level or "INFO"
        spl_comment = f"# SPL: LOGGING {self._spl_expr(stmt.expression)} LEVEL {level}"
        code = f"{spl_comment}\nprint('[{level}]', {msg})"
        return _code_cell(code, metadata={"tags": ["logging"]})

    # ── Recursive body renderer (for OTHERWISE / WHILE / EVALUATE bodies) ────

    def _body_to_python(self, stmts: list, indent: str = "    ") -> list[str]:
        """Render a list of statements as indented Python lines."""
        lines: list[str] = []
        for stmt in stmts:
            cells = self._stmt_to_cells(stmt)
            for cell in cells:
                if cell["cell_type"] == "code":
                    src = "".join(cell["source"])
                    for ln in src.splitlines():
                        lines.append(indent + ln)
        return lines

    # ── Expression renderers ──────────────────────────────────────────────────

    def _expr_py(self, expr) -> str:
        """Render an SPL expression as a plain Python expression (no state[])."""
        if isinstance(expr, ParamRef):
            return self._key(expr.name)
        if isinstance(expr, str):
            if expr.startswith("@"):
                return self._key(expr)
            return repr(expr)
        if isinstance(expr, Literal):
            if isinstance(expr.value, str):
                return repr(expr.value)
            return str(expr.value)
        if isinstance(expr, NoneLiteral):
            return "None"
        if isinstance(expr, FStringLiteral):
            return self._fstr_py(expr.template)
        if isinstance(expr, NamedArg):
            return f"{expr.name}={self._expr_py(expr.value)}"
        if isinstance(expr, UnaryOp):
            return f"not ({self._expr_py(expr.operand)})"
        if isinstance(expr, BinaryOp):
            left  = self._expr_py(expr.left)
            right = self._expr_py(expr.right)
            return f"{left} {expr.op} {right}"
        if isinstance(expr, CompoundCondition):
            parts = [self._render_condition(c) for c in expr.conditions]
            op = " and " if expr.conjunctions and expr.conjunctions[0] == "AND" else " or "
            return op.join(parts)
        return f"# EXPR({type(expr).__name__})"

    def _spl_arg(self, arg) -> str:
        """Render SPL argument for comment traceability."""
        if isinstance(arg, ParamRef):
            return f"@{self._key(arg.name)}"
        if isinstance(arg, Literal):
            return repr(arg.value)
        if isinstance(arg, str):
            return f"@{self._key(arg)}" if arg.startswith("@") else repr(arg)
        if isinstance(arg, NamedArg):
            return f"{arg.name}={self._spl_arg(arg.value)}"
        return str(arg)

    def _spl_expr(self, expr) -> str:
        """Render an SPL expression in SPL syntax (for comments)."""
        if isinstance(expr, ParamRef):
            return f"@{self._key(expr.name)}"
        if isinstance(expr, Literal):
            return repr(expr.value)
        if isinstance(expr, str):
            return expr
        return self._spl_arg(expr)

    def _fstr_py(self, template: str) -> str:
        """'{@var}/text_{@n}.md' → f'{var}/text_{n}.md'"""
        result = re.sub(r"\{@(\w+)\}", r"{\1}", template)
        result = re.sub(r"@(\w+)", r"\1", result)
        result = result.replace('"', '\\"')
        return f'f"{result}"'

    def _render_condition(self, cond) -> str:
        """Render a WHILE/ASSERT condition as Python."""
        if isinstance(cond, SemanticCondition):
            return f'"{cond.semantic_value}" not in str(_last_result).lower()'
        if isinstance(cond, CompoundCondition):
            parts = [self._render_condition(c) for c in cond.conditions]
            op = " and " if cond.conjunctions and cond.conjunctions[0] == "AND" else " or "
            return op.join(parts)
        if hasattr(cond, "operator") and hasattr(cond, "right"):
            right = self._expr_py(cond.right)
            return f"_cond_var {cond.operator} {right}"
        return self._expr_py(cond)

    def _spl_condition(self, cond) -> str:
        """Render a condition in SPL syntax for comment."""
        if isinstance(cond, SemanticCondition):
            return cond.semantic_value
        return str(cond)

    def _render_when_condition(self, cond, subject_var: str) -> str:
        """Render a WHEN <cond> condition in the context of an EVALUATE subject."""
        if isinstance(cond, SemanticCondition):
            val = cond.semantic_value.lower()
            return f'"{val}" in str({subject_var}).lower()'
        if hasattr(cond, "operator") and hasattr(cond, "right"):
            right = self._expr_py(cond.right)
            return f"{subject_var} {cond.operator} {right}"
        return self._render_condition(cond)

    @staticmethod
    def _key(var_name: str) -> str:
        return var_name.lstrip("@")


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _subst_markers(template: str) -> str:
    """@@varname@@ → varname  (undo parser's @var → @@varname@@ encoding)."""
    return re.sub(r"@@(\w+)@@", r"\1", template)


def _markers_to_at(template: str) -> str:
    """@@varname@@ → @varname  (human-readable SPL form for comments)."""
    return re.sub(r"@@(\w+)@@", r"@\1", template)
