"""tools.py — Notebook assembly helper for recipe 69.

Registered via --tools and called from notebook_gen.spl as:
    CALL assemble_notebook(@topic, @matrix_a, ...) INTO @path

Keeps all text handling in Python so SPL f-strings only carry
simple values — no escaping of LLM-generated prose required.
"""

import json
from pathlib import Path

from spl.tools import spl_tool


@spl_tool
def assemble_notebook(
    topic: str,
    matrix_a: str,
    intro_text: str,
    explanation_text: str,
    eigen_summary: str,
    verification: str,
    output_path: str,
) -> str:
    """Build a Jupyter notebook from the workflow's collected pieces.

    Returns the absolute path to the written .ipynb file.
    """

    def md(source: str) -> dict:
        return {
            "cell_type": "markdown",
            "metadata": {},
            "source": source.strip(),
        }

    def code(source: str) -> dict:
        return {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": source.strip(),
        }

    # Format eigen summary as a readable table
    eigen_lines = eigen_summary.replace(" | ", "\n").replace(", v=", " → v=")

    cells = [
        # ── Title + intro ──────────────────────────────────────
        md(f"# {topic.title()}\n\n{intro_text}"),

        # ── Setup code cell ────────────────────────────────────
        code(
            "import sympy as sp\n"
            "\n"
            f"A = sp.Matrix({matrix_a})\n"
            "print('Matrix A:')\n"
            "A"
        ),

        # ── Eigendecomposition ─────────────────────────────────
        md("## Eigendecomposition\n\nCompute eigenvalues and eigenvectors exactly using SymPy:"),

        code(
            "eigendata = A.eigenvects()\n"
            "for lam, mult, vecs in eigendata:\n"
            "    for v in vecs:\n"
            "        print(f'λ = {lam},  v = {v.T}')"
        ),

        # ── SPL-computed summary ────────────────────────────────
        md(
            f"**Computed by the SPL kernel during workflow execution:**\n\n"
            f"```\n{eigen_lines}\n```"
        ),

        # ── LLM explanation ────────────────────────────────────
        md(f"## What Do These Values Mean?\n\n{explanation_text}"),

        # ── Verification ───────────────────────────────────────
        md("## Verification: A·v = λ·v\n\nConfirm each eigenpair satisfies the defining equation:"),

        code(
            "for lam, mult, vecs in eigendata:\n"
            "    for v in vecs:\n"
            "        result = A * v == lam * v\n"
            "        print(f'λ={lam}: A·v == λ·v → {result}')"
        ),

        # ── Verification result from kernel ────────────────────
        md(
            f"**Verified deterministically by the SPL kernel:**\n\n"
            f"`{verification}`\n\n"
            f"> All checks pass — SymPy confirmed exact equality, not floating-point approximation."
        ),

        # ── Provenance note ────────────────────────────────────
        md(
            "---\n\n"
            "*This notebook was generated by an SPL workflow (`notebook_gen.spl`).*\n"
            "*Mathematical content: deterministic (SymPy via IPython kernel).*\n"
            "*Prose content: probabilistic (LLM via SPL `GENERATE`).*"
        ),
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "cells": cells,
    }

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(notebook, indent=2, ensure_ascii=False), encoding="utf-8")

    abs_path = str(out.resolve())
    print(f"wrote {len(cells)} cells → {abs_path}")
    return abs_path
