"""
structured_debate — generated by splc (deterministic Python/PocketFlow transpiler)

PocketFlow pattern: prep(shared) → exec(prep_res) → post(shared, prep_res, exec_res)
                    Extract       → Transform        → Load
                    (ETL applied to LLM orchestration)

Pattern: step1 → step2 → ... → output

Usage:
    pip install pocketflow click
    python structured_debate_python_pocketflow.py --task "Your task here"
"""

from pathlib import Path

import click
from pocketflow import Flow, Node

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

ADVOCATE_FOR_PROMPT = """\
Generate supporting arguments for the following claim using evidence and reasoning.
Return your response in YAML format with the following structure:
arguments:
  - point: "argument point"
    evidence: "supporting evidence"
    reasoning: "logical reasoning"
key_points:
  - "summary point 1"
  - "summary point 2"

Claim: {claim}"""

ADVOCATE_AGAINST_PROMPT = """\
Generate rebuttals and counterarguments against the following claim, considering the arguments already made in favor.
Return your response in YAML format with the following structure:
arguments:
  - point: "counterargument point"
    evidence: "contradicting evidence"
    reasoning: "logical reasoning"
rebuttals:
  - original_point: "point being rebutted"
    rebuttal: "specific rebuttal"
key_points:
  - "summary point 1"
  - "summary point 2"

Claim: {claim}
Case For: {case_for}"""

JUDGE_DEBATE_PROMPT = """\
Evaluate both sides of the debate and declare a winner with numerical scores.
Return your response in YAML format with the following structure:
evaluation:
  case_for_score: 85
  case_against_score: 72
  winner: "for"
  reasoning: "explanation of decision"
verdict:
  conclusion: "final judgment"
  confidence: 0.85

Claim: {claim}
Case For: {case_for}
Case Against: {case_against}"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _call_llm(model: str, prompt: str) -> str:
    """Call the LLM via Ollama REST API. Replace with your preferred adapter."""
    import urllib.request, json
    payload = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["response"].strip()


def _write(path: str, content: str) -> None:
    """Write content to a file, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ── Nodes  (each mirrors one GENERATE / CALL statement) ────────────────────

class Step1_Advocate_forNode(Node):
    # SPL: GENERATE advocate_for(...) INTO @case_for

    def prep(self, shared):
        # Extract — pull required vars from shared store
        claim = shared["claim"]
        return claim

    def exec(self, prep_res):
        # Transform — LLM call: advocate_for
        claim = prep_res
        print("Running advocate_for ...")
        return _call_llm("llama3.2", ADVOCATE_FOR_PROMPT.format(claim=claim))

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["case_for"] = exec_res
        return "step2"

class Step2_Advocate_againstNode(Node):
    # SPL: GENERATE advocate_against(...) INTO @case_against

    def prep(self, shared):
        # Extract — pull required vars from shared store
        claim = shared["claim"]
        case_for = shared["case_for"]
        return claim, case_for

    def exec(self, prep_res):
        # Transform — LLM call: advocate_against
        claim, case_for = prep_res
        print("Running advocate_against ...")
        return _call_llm("llama3.2", ADVOCATE_AGAINST_PROMPT.format(claim=claim, case_for=case_for))

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["case_against"] = exec_res
        return "step3"

class Step3_Judge_debateNode(Node):
    # SPL: GENERATE judge_debate(...) INTO @verdict

    def prep(self, shared):
        # Extract — pull required vars from shared store
        claim = shared["claim"]
        case_for = shared["case_for"]
        case_against = shared["case_against"]
        return claim, case_for, case_against

    def exec(self, prep_res):
        # Transform — LLM call: judge_debate
        claim, case_for, case_against = prep_res
        print("Running judge_debate ...")
        return _call_llm("llama3.2", JUDGE_DEBATE_PROMPT.format(claim=claim, case_for=case_for, case_against=case_against))

    def post(self, shared, prep_res, exec_res):
        # Load — store result
        shared["verdict"] = exec_res
        shared["status"] = "complete"
        print(f"\nStatus:  complete")
        print(f"\n{shared.get('verdict', exec_res)}")
        return None

# ── Flow wiring  (mirrors WORKFLOW control flow) ─────────────────────────────
# SPL: sequential GENERATE/CALL chain — linear pipeline

def build_flow() -> Flow:
    step1 = Step1_Advocate_forNode()
    step2 = Step2_Advocate_againstNode()
    step3 = Step3_Judge_debateNode()

    step1 - "step2" >> step2
    step2 - "step3" >> step3
    return Flow(start=step1)

# ── Entry point  (SPL: built into CLI — `spl3 run ...`) ────────────────────────

@click.command()
@click.option("--claim", required=True)
def main(claim: str):
    # SPL: INPUT @vars → shared store (ETL staging area)
    shared = {
        "claim": claim,
    }
    build_flow().run(shared)


if __name__ == "__main__":
    main()