# parallel_code_review.py — AutoGen implementation of parallel_code_review.spl
# Generated by splc (SPL Compiler) — target: Python / AutoGen 0.2.x

import asyncio
import logging
import os
import sys

import openai
from autogen import AssistantAgent, UserProxyAgent

# ── Logging setup ─────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


# ── LLM config factory ────────────────────────────────────────────────────────

def _llm_config(model: str, max_tokens: int = 2048) -> dict:
    """Build an AutoGen llm_config dict for a given model and token budget."""
    return {
        "config_list": [
            {
                "model": model,
                "base_url": os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
                "api_key": "ollama",
            }
        ],
        "max_tokens": max_tokens,
        "cache_seed": None,  # disable caching so parallel calls don't collide
    }


async def _single_turn(system: str, user: str, model: str, max_tokens: int = 2048) -> str:
    """
    Issue one LLM call through an AutoGen AssistantAgent and return its reply.
    Used by all sub-workflows and the merge step — keeps agents stateless.
    """
    agent = AssistantAgent(
        name="worker",
        system_message=system,
        llm_config=_llm_config(model, max_tokens=max_tokens),
        human_input_mode="NEVER",
        max_consecutive_auto_reply=1,
    )
    # generate_reply accepts the OpenAI messages list format directly
    reply = await agent.a_generate_reply(
        messages=[{"role": "user", "content": user}]
    )
    return reply if isinstance(reply, str) else (reply or "")


# ── SPL: IMPORT '00_style_review' ─────────────────────────────────────────────

async def style_review(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL style_review(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb
    system = (
        f"You are an expert {lang} code style reviewer. "
        "Analyse the code for style issues, readability, naming conventions, "
        "language idioms, and logical correctness. "
        "Output a concise bullet list; label each item CRITICAL, MODERATE, or LOW."
    )
    user = f"Review the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: IMPORT '01_security_audit' ───────────────────────────────────────────

async def security_audit(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL security_audit(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb
    system = (
        f"You are a security engineer specialising in {lang} application security. "
        "Audit the code for vulnerabilities: injection flaws, insecure defaults, "
        "improper error handling, hard-coded secrets, and OWASP Top-10 risks. "
        "Output a concise bullet list; label each item CRITICAL, MODERATE, or LOW."
    )
    user = f"Security-audit the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: IMPORT '02_test_generator' ───────────────────────────────────────────

async def test_generator(
    code: str, lang: str, review_model: str, log_dir: str
) -> str:
    # SPL: CALL test_generator(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
    system = (
        f"You are a senior {lang} engineer specialising in test-driven development. "
        "Generate a comprehensive unit-test suite covering happy paths, edge cases, "
        "and error conditions. "
        f"Output only runnable {lang} test code inside a single fenced code block."
    )
    user = f"Generate unit tests for the following {lang} code:\n\n```{lang}\n{code}\n```"
    return await _single_turn(system, user, review_model)


# ── SPL: CREATE FUNCTION merge_reviews(style TEXT, sec_audit TEXT, tests TEXT) RETURN TEXT AS $$ … $$ ──

_MERGE_REVIEWS_SYSTEM = (
    "You are a senior engineering lead who writes precise, concise technical reports."
)

_MERGE_REVIEWS_TEMPLATE = """\
You are a senior engineering lead consolidating three independent code-review reports
into a single, actionable plan.

Style & Correctness Review:
{style}

Security Audit:
{sec_audit}

Generated Test Cases:
{tests}

Produce a consolidated report with three sections:
1. **Action Items** — numbered list of changes to make, CRITICAL first, then MODERATE, then LOW
2. **Test Coverage** — paste the generated tests verbatim under a code block
3. **Summary** — one paragraph overall assessment (is this code production-ready?)

Keep the Action Items section under 150 words.\
"""


async def _merge_reviews(
    style: str, sec_audit: str, tests: str, review_model: str
) -> str:
    # SPL: GENERATE merge_reviews(@style_fb, @sec_fb, @test_fb)
    #       WITH OUTPUT BUDGET 1024 TOKENS
    #       USING MODEL @review_model
    #       INTO @report
    user = _MERGE_REVIEWS_TEMPLATE.format(
        style=style, sec_audit=sec_audit, tests=tests
    )
    return await _single_turn(
        _MERGE_REVIEWS_SYSTEM, user, review_model, max_tokens=1024  # OUTPUT BUDGET 1024 TOKENS
    )


# ── SPL: WORKFLOW parallel_code_review ────────────────────────────────────────

async def parallel_code_review(
    code: str,
    lang: str = "python",                                         # SPL INPUT: @lang TEXT DEFAULT 'python'
    review_model: str = "gemma3",                                 # SPL INPUT: @review_model TEXT DEFAULT 'gemma3'
    log_dir: str = "cookbook/63_parallel_code_review/logs-spl",   # SPL INPUT: @log_dir TEXT DEFAULT '...'
) -> str:
    """
    SPL: WORKFLOW parallel_code_review
         OUTPUT: @report TEXT
    """
    report: str = ""  # SPL: OUTPUT @report TEXT

    try:
        # SPL: LOGGING f'[parallel_code_review] starting 3-way parallel review | lang={@lang} ...' LEVEL INFO
        log.info(
            "[parallel_code_review] starting 3-way parallel review | "
            "lang=%s review_model=%s",
            lang, review_model,
        )

        # SPL: CALL PARALLEL
        #   style_review   (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb,
        #   security_audit (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb,
        #   test_generator (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
        # END
        style_fb, sec_fb, test_fb = await asyncio.gather(
            style_review(code, lang=lang, review_model=review_model, log_dir=log_dir),
            security_audit(code, lang=lang, review_model=review_model, log_dir=log_dir),
            test_generator(code, lang=lang, review_model=review_model, log_dir=log_dir),
        )

        # SPL: LOGGING '[parallel_code_review] parallel checks complete — merging into report' LEVEL INFO
        log.info("[parallel_code_review] parallel checks complete — merging into report")

        report = await _merge_reviews(
            style=style_fb,
            sec_audit=sec_fb,
            tests=test_fb,
            review_model=review_model,
        )

        # SPL: LOGGING f'[parallel_code_review] done | report_len={len(@report)}' LEVEL INFO
        log.info("[parallel_code_review] done | report_len=%d", len(report))

        # SPL: COMMIT @report
        return report

    # SPL: EXCEPTION WHEN ModelUnavailable THEN
    except (openai.APIConnectionError, openai.AuthenticationError) as exc:
        # SPL: LOGGING f'[parallel_code_review] model unavailable: {@review_model}' LEVEL ERROR
        log.error(
            "[parallel_code_review] model unavailable: %s — %s", review_model, exc
        )
        # SPL: RETURN '[ERROR] Model unavailable.' WITH status = 'failed'
        return "[ERROR] Model unavailable."

    # SPL: EXCEPTION WHEN BudgetExceeded THEN
    except openai.BadRequestError as exc:
        if "context" not in str(exc).lower() and "token" not in str(exc).lower():
            raise
        # SPL: LOGGING '[parallel_code_review] token budget exceeded during merge' LEVEL WARN
        log.warning("[parallel_code_review] token budget exceeded during merge")
        # SPL: COMMIT @report WITH status = 'truncated'
        return report  # return whatever was accumulated before truncation


# ── CLI entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Parallel Code Review — AutoGen implementation of parallel_code_review.spl"
    )
    parser.add_argument(
        "--code", required=True,
        help="Source code to review (use $(cat file.py) to pass a file)",
    )
    parser.add_argument(
        "--lang", default="python",
        help="Programming language (default: python)",
    )
    parser.add_argument(
        "--review-model", default="gemma3", dest="review_model",
        help="LLM model name served by Ollama (default: gemma3)",
    )
    parser.add_argument(
        "--log-dir",
        default="cookbook/63_parallel_code_review/logs-spl",
        dest="log_dir",
        help="Log directory (unused by this adapter; kept for SPL INPUT parity)",
    )
    args = parser.parse_args()

    result = asyncio.run(
        parallel_code_review(
            code=args.code,
            lang=args.lang,
            review_model=args.review_model,
            log_dir=args.log_dir,
        )
    )
    print(result)