"""Report rendering for spl3 judge."""

from __future__ import annotations
import json

from spl3.judge.types import JudgeResult, PanelResult


_VERDICT_ICON = {"PASS": "✅", "FAIL": "❌", "ESCALATE": "⚠️"}
_CONF_ICON    = {"HIGH": "🟢", "MEDIUM": "🟡", "LOW": "🔴"}
_CONS_ICON    = {"UNANIMOUS": "🤝", "MAJORITY": "🗳️", "SPLIT": "⚡"}


def render_judge_report(
    result: JudgeResult | PanelResult,
    output_format: str = "markdown",
) -> str:
    if isinstance(result, PanelResult):
        if output_format == "json":
            return _render_panel_json(result)
        if output_format == "text":
            return _render_panel_text(result)
        return _render_panel_markdown(result)

    if output_format == "json":
        return _render_json(result)
    if output_format == "text":
        return _render_text(result)
    return _render_markdown(result)


# ── Single judge ──────────────────────────────────────────────────────────────

def _render_json(r: JudgeResult) -> str:
    return json.dumps({
        "verdict":         r.verdict,
        "score":           r.score,
        "confidence":      r.confidence,
        "rubric":          r.rubric,
        "adapter":         r.adapter,
        "model":           r.model,
        "criteria_scores": r.criteria_scores,
        "reasoning":       r.reasoning,
        "feedback":        r.feedback,
        "swap_consistent": r.swap_consistent,
    }, indent=2)


def _render_text(r: JudgeResult) -> str:
    lines = [
        f"Verdict: {r.verdict} ({r.confidence} confidence)",
        f"Score:   {r.score:.1f} / 10",
        f"Rubric:  {r.rubric}",
        f"Judge:   {r.adapter}:{r.model}",
        "",
    ]
    if r.criteria_scores:
        lines.append("Criteria scores:")
        for c, s in r.criteria_scores.items():
            lines.append(f"  {c}: {s:.1f}")
    if r.feedback:
        lines += ["", f"Feedback: {r.feedback}"]
    if r.swap_consistent is not None:
        lines.append(f"Swap-consistent: {r.swap_consistent}")
    return "\n".join(lines)


def _render_markdown(r: JudgeResult) -> str:
    icon  = _VERDICT_ICON.get(r.verdict, "🔍")
    cicon = _CONF_ICON.get(r.confidence, "")
    lines = [
        f"# Judge Report: {icon} {r.verdict}",
        "",
        f"- **Score:** {r.score:.1f} / 10",
        f"- **Confidence:** {cicon} {r.confidence}",
        f"- **Rubric:** `{r.rubric}`",
        f"- **Judge:** `{r.adapter}:{r.model}`",
    ]
    if r.swap_consistent is not None:
        sc_icon = "✓" if r.swap_consistent else "✗"
        lines.append(f"- **Swap-consistent:** {sc_icon} {r.swap_consistent}")
    lines.append("")

    if r.criteria_scores:
        lines += ["## Criteria Scores", "",
                  "| Criterion | Score |", "|-----------|-------|"]
        for c, s in r.criteria_scores.items():
            lines.append(f"| {c} | {s:.1f} |")
        lines.append("")

    if r.reasoning:
        lines += ["## Reasoning", "", r.reasoning, ""]
    if r.feedback:
        lines += ["## Feedback", "", r.feedback, ""]

    lines += ["---", "*Generated by `spl3 judge`*"]
    return "\n".join(lines)


# ── Panel ─────────────────────────────────────────────────────────────────────

def _render_panel_json(r: PanelResult) -> str:
    return json.dumps({
        "verdict":     r.verdict,
        "score":       r.score,
        "confidence":  r.confidence,
        "consensus":   r.consensus,
        "aggregation": r.aggregation,
        "rubric":      r.rubric,
        "dissent":     r.dissent,
        "swap_consistent": r.swap_consistent,
        "individual": [
            {
                "verdict":         m.verdict,
                "score":           m.score,
                "confidence":      m.confidence,
                "adapter":         m.adapter,
                "model":           m.model,
                "criteria_scores": m.criteria_scores,
                "feedback":        m.feedback,
                "swap_consistent": m.swap_consistent,
            }
            for m in r.individual
        ],
    }, indent=2)


def _render_panel_text(r: PanelResult) -> str:
    lines = [
        f"Panel Verdict: {r.verdict} ({r.confidence} confidence)",
        f"Score:         {r.score:.1f} / 10",
        f"Consensus:     {r.consensus}  Aggregation: {r.aggregation}",
        f"Rubric:        {r.rubric}",
        "",
        "Individual judges:",
    ]
    for m in r.individual:
        lines.append(f"  {m.adapter}:{m.model}  →  {m.verdict} ({m.score:.1f})")
    if r.dissent:
        lines += ["", f"Dissent: {r.dissent}"]
    if r.swap_consistent is not None:
        lines.append(f"Swap-consistent: {r.swap_consistent}")
    return "\n".join(lines)


def _render_panel_markdown(r: PanelResult) -> str:
    icon  = _VERDICT_ICON.get(r.verdict, "🔍")
    cicon = _CONF_ICON.get(r.confidence, "")
    kicon = _CONS_ICON.get(r.consensus, "")

    lines = [
        f"# Panel Judge Report: {icon} {r.verdict}",
        "",
        f"- **Score:** {r.score:.1f} / 10",
        f"- **Confidence:** {cicon} {r.confidence}",
        f"- **Consensus:** {kicon} {r.consensus}",
        f"- **Aggregation:** `{r.aggregation}`",
        f"- **Rubric:** `{r.rubric}`",
        f"- **Panel size:** {len(r.individual)}",
    ]
    if r.swap_consistent is not None:
        sc_icon = "✓" if r.swap_consistent else "✗"
        lines.append(f"- **Swap-consistent:** {sc_icon} {r.swap_consistent}")
    lines.append("")

    lines += ["## Panel Members", ""]
    lines += [
        "| Judge | Verdict | Score | Confidence |",
        "|-------|---------|-------|------------|",
    ]
    for m in r.individual:
        v_icon = _VERDICT_ICON.get(m.verdict, "")
        lines.append(
            f"| `{m.adapter}:{m.model}` | {v_icon} {m.verdict} "
            f"| {m.score:.1f} | {m.confidence} |"
        )
    lines.append("")

    if r.dissent:
        lines += ["## Dissent", "", r.dissent, ""]

    # Aggregate criteria scores (mean across panel)
    if r.individual and r.individual[0].criteria_scores:
        criteria = list(r.individual[0].criteria_scores.keys())
        lines += ["## Criteria Scores (mean across panel)", "",
                  "| Criterion | Mean | " + " | ".join(
                      f"`{m.adapter}:{m.model}`" for m in r.individual
                  ) + " |"]
        sep = "|-----------|------|" + "|------|" * len(r.individual)
        lines.append(sep)
        for c in criteria:
            scores = [m.criteria_scores.get(c, 0.0) for m in r.individual]
            mean   = sum(scores) / len(scores)
            cells  = " | ".join(f"{s:.1f}" for s in scores)
            lines.append(f"| {c} | **{mean:.1f}** | {cells} |")
        lines.append("")

    lines += ["---", "*Generated by `spl3 judge` (panel mode)*"]
    return "\n".join(lines)
