"""
self_refine — generated by splc (deterministic Python/PocketFlow transpiler)

PocketFlow pattern: prep(shared) → exec(prep_res) → post(shared, prep_res, exec_res)
                    Extract       → Transform        → Load
                    (ETL applied to LLM orchestration)

Pattern: draft → critique → ([APPROVED]? commit : refine → critique)

Usage:
    pip install pocketflow click
    python self_refine_python_pocketflow.py --task "Your task here"
"""

from pathlib import Path

import click
from pocketflow import Flow, Node

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

DRAFT_PROMPT = """\
You are an expert writer. Complete the following task thoroughly and well.

Task: {task}

Write a high-quality response now."""

CRITIQUE_PROMPT = """\
You are a strict critic reviewing written content.

If the content fully meets the bar with no meaningful improvements needed,
reply with exactly this token and nothing else: [APPROVED]

Otherwise, provide specific, actionable feedback on how to improve it.
Do NOT output [APPROVED] unless the content truly needs no further work.

Content to review:
{current}"""

REFINE_PROMPT = """\
You are an expert writer. Improve the following draft based on the feedback.

Draft:
{current}

Feedback:
{feedback}

Write the improved version now."""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _call_llm(model: str, prompt: str) -> str:
    """Call the LLM via Ollama REST API. Replace with your preferred adapter."""
    import urllib.request, json
    payload = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["response"].strip()


def _write(path: str, content: str) -> None:
    """Write content to a file, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ── Nodes  (each mirrors one GENERATE / EVALUATE block) ──────────────────────

class DraftNode(Node):
    # SPL: initial GENERATE draft(...) INTO @current

    def prep(self, shared):
        # Extract — pull INPUT vars from shared store
        task = shared["task"]
        output_budget = shared["output_budget"]
        max_iterations = shared["max_iterations"]
        writer_model = shared["writer_model"]
        critic_model = shared["critic_model"]
        log_dir = shared["log_dir"]
        return task, output_budget, max_iterations, writer_model, critic_model, log_dir

    def exec(self, prep_res):
        # Transform — LLM call
        task, output_budget, max_iterations, writer_model, critic_model, log_dir = prep_res
        print("Generating initial draft ...")
        return _call_llm(writer_model, DRAFT_PROMPT.format(task=task))

    def post(self, shared, prep_res, exec_res):
        # Load — write results back to shared store
        shared["current"] = exec_res
        shared["iteration"] = 0
        print(f"Self-refine started | max_iterations={shared['max_iterations']} for task:\n {shared['task']} ...")
        print('Initial draft ready')
        _write(f"{shared['log_dir']}/draft_0.md", shared["current"])
        return "critique"

class CritiqueNode(Node):
    # SPL: GENERATE critique(@current) INTO @feedback
    # post() mirrors EVALUATE @feedback WHEN contains("[APPROVED]") + WHILE guard

    def prep(self, shared):
        # Extract — pull current draft, iteration counter, and model
        return shared["current"], shared.get("iteration", 0), shared.get("critic_model", "llama3.2")

    def exec(self, prep_res):
        # Transform — LLM critique call
        current, _, model = prep_res
        print("Critiquing current draft ...")
        return _call_llm(model, CRITIQUE_PROMPT.format(current=current))

    def post(self, shared, prep_res, exec_res):
        # Load — save feedback; route based on EVALUATE + WHILE guard
        shared["feedback"] = exec_res
        _, i, _ = prep_res
        print(f"Iteration {shared['iteration']} | critiquing ...")
        _write(f"{shared['log_dir']}/feedback_{i}.md", exec_res)
        if '[APPROVED]' in exec_res:
            print(f"Approved at iteration {i}")
            return "commit"
        if i >= shared.get("max_iterations", 3):
            print(f"Max iterations reached | iterations={i}")
            return "commit"
        return "refine"

class RefineNode(Node):
    # SPL: GENERATE refine(@current, @feedback) INTO @current

    def prep(self, shared):
        # Extract — pull current draft, feedback, iteration counter, and model
        return shared["current"], shared["feedback"], shared.get("iteration", 0), shared.get("writer_model", "llama3.2")

    def exec(self, prep_res):
        # Transform — LLM refinement call
        current, feedback, _, model = prep_res
        print("Refining draft ...")
        return _call_llm(model, REFINE_PROMPT.format(current=current, feedback=feedback))

    def post(self, shared, prep_res, exec_res):
        # Load — update draft and increment iteration counter
        shared["current"] = exec_res
        shared["iteration"] = prep_res[2] + 1
        print(f"Refined | iteration={shared['iteration']}")
        _write(f"{shared['log_dir']}/draft_{shared['iteration']}.md", shared["current"])
        return "critique"

class CommitNode(Node):
    # SPL: RETURN @current WITH status, iterations

    def prep(self, shared):
        return shared.get("current", ""), shared.get("iteration", 0), shared.get("feedback", "")

    def exec(self, prep_res):
        return prep_res

    def post(self, shared, prep_res, exec_res):
        # Load — write final output and log status
        current, i, feedback = exec_res
        _write(f"{shared['log_dir']}/final.md", shared["current"])
        approved = shared.get("feedback", "") and "[APPROVED]" in shared.get("feedback", "")
        status = "complete" if approved else "max_iterations"
        print(f"\nStatus:     {status}")
        print(f"Iterations: {i}")
        print(f"\n{current}")
        shared["status"] = status
        return None

# ── Flow wiring  (mirrors WORKFLOW control flow) ─────────────────────────────
# SPL:  draft → WHILE loop → EVALUATE → commit or refine → critique
#
# PocketFlow conditional edges via post() return value (action string):
#   critique.post() → "commit"  (EVALUATE [APPROVED] or max_iterations)
#   critique.post() → "refine"  (else branch)
#   refine.post()   → "critique" (loop back)
#   draft.post()    → "critique" (initial transition)

def build_flow() -> Flow:
    draft   = DraftNode()
    critique = CritiqueNode()
    refine  = RefineNode()
    commit  = CommitNode()

    # SPL: initial draft → critique
    draft   - "critique" >> critique

    # SPL: EVALUATE + WHILE guard → commit or refine
    critique - "commit"  >> commit
    critique - "refine"  >> refine

    # SPL: WHILE back-edge — refine → critique
    refine  - "critique" >> critique

    return Flow(start=draft)

# ── Entry point  (SPL: built into CLI — `spl3 run ...`) ────────────────────────

@click.command()
@click.option("--task", default='What are the benefits of meditation?', show_default=True)
@click.option("--output-budget", default=2000, show_default=True, type=int)
@click.option("--max-iterations", default=3, show_default=True, type=int)
@click.option("--writer-model", default='gemma3', show_default=True)
@click.option("--critic-model", default='llama3.2', show_default=True)
@click.option("--log-dir", default='cookbook/05_self_refine/logs-spl', show_default=True)
def main(task: str, output_budget: int, max_iterations: int, writer_model: str, critic_model: str, log_dir: str):
    # SPL: INPUT @vars → shared store (ETL staging area)
    shared = {
        "task": task,
        "output_budget": output_budget,
        "max_iterations": max_iterations,
        "writer_model": writer_model,
        "critic_model": critic_model,
        "log_dir": log_dir,
        "iteration": 0,
        "current": "",
        "feedback": "",
    }
    build_flow().run(shared)


if __name__ == "__main__":
    main()