"""
parallel_code_review — generated by splc (deterministic Python/LangGraph transpiler)

Pattern: CALL PARALLEL fan-out → merge → commit

Usage:
    pip install langgraph langchain-ollama click
    python parallel_code_review_python_langgraph.py --code "Your code here"
"""

import asyncio
from pathlib import Path
from typing import TypedDict

import click

from langchain_ollama import ChatOllama
from langgraph.graph import END, StateGraph

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

STYLE_REVIEW_PROMPT = """\
You are a senior {lang} engineer conducting a code review focused on
style, readability, and correctness.

Review the following {lang} code:

{code}

Provide feedback on:
1. Naming conventions and clarity
2. Code structure and organisation
3. Potential logic errors or edge cases
4. Adherence to idiomatic {lang} patterns

Format: numbered list, most important issues first.
Keep your review under 200 words."""

SECURITY_AUDIT_PROMPT = """\
You are a security engineer conducting a static analysis of {lang} code.

Review the following {lang} code for security vulnerabilities:

{code}

Check for (where applicable):
1. Injection risks (SQL, command, path traversal)
2. Insecure input validation or missing bounds checks
3. Hard-coded credentials or secrets
4. Insecure use of cryptographic primitives
5. Race conditions or unsafe concurrency
6. Excessive permissions or privilege escalation paths

Format: numbered list, CRITICAL issues first, then MODERATE, then LOW.
If no issues found, say "No security issues detected."
Keep your audit under 200 words."""

TEST_GENERATOR_PROMPT = """\
You are a test engineer writing unit tests for {lang} code.

Generate unit test cases for the following {lang} code:

{code}

Requirements:
- Cover the happy path (expected inputs and outputs)
- Cover at least two edge cases (empty input, boundary values, None/null, etc.)
- Cover at least one error/exception path if applicable
- Use the standard testing framework for {lang}
  (pytest for Python, testing package for Go, jest for TypeScript/JavaScript)

Output only the test code, no explanation. Include import statements."""

MERGE_REVIEWS_PROMPT = """\
You are a senior engineering lead consolidating three independent code-review reports
into a single, actionable plan.

Style & Correctness Review:
{style}

Security Audit:
{sec_audit}

Generated Test Cases:
{tests}

Produce a consolidated report with three sections:
1. **Action Items** — numbered list of changes to make, CRITICAL first, then MODERATE, then LOW
2. **Test Coverage** — paste the generated tests verbatim under a code block
3. **Summary** — one paragraph overall assessment (is this code production-ready?)

Keep the Action Items section under 150 words."""

# ── State  (SPL manages @variables implicitly) ────────────────────────────────

class ParallelCodeReviewState(TypedDict):
    code:                 str
    lang:                 str  # default: 'python'
    review_model:         str  # default: 'gemma4'
    log_dir:              str  # default: 'cookbook/63_parallel_code_review/logs-spl'
    # runtime variables
    report:               str
    sec_fb:               str
    style_fb:             str
    test_fb:              str

# ── Helpers ───────────────────────────────────────────────────────────────────

async def _invoke_async(model: str, prompt: str) -> str:
    return await asyncio.to_thread(
        lambda: ChatOllama(model=model).invoke(prompt).content.strip()
    )

def _invoke(model: str, prompt: str) -> str:
    return ChatOllama(model=model).invoke(prompt).content.strip()

def _write(path: str, content: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ── Nodes  (each mirrors one SPL statement block) ──────────────────────────

def node_parallel(state: ParallelCodeReviewState) -> dict:
    # SPL: CALL PARALLEL
    #   style_review(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb
    #   security_audit(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb
    #   test_generator(@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
    print(f"[parallel_code_review] starting 3-way parallel review | lang={state['lang']} review_model={state['review_model']}")
    async def _run():
        style_fb, sec_fb, test_fb = await asyncio.gather(
            _invoke_async(state["review_model"], STYLE_REVIEW_PROMPT.format(code=state["code"], lang=state["lang"])),
            _invoke_async(state["review_model"], SECURITY_AUDIT_PROMPT.format(code=state["code"], lang=state["lang"])),
            _invoke_async(state["review_model"], TEST_GENERATOR_PROMPT.format(code=state["code"], lang=state["lang"])),
        )
        return style_fb, sec_fb, test_fb

    style_fb, sec_fb, test_fb = asyncio.run(_run())
    print(f"[style_review] lang={state['lang']}")
    print(f"[security_audit] lang={state['lang']}")
    print(f"[test_generator] lang={state['lang']}")
    return {"style_fb": style_fb, "sec_fb": sec_fb, "test_fb": test_fb}

def node_merge(state: ParallelCodeReviewState) -> dict:
    # SPL: GENERATE merge_reviews(@style_fb, @sec_fb, @test_fb) USING MODEL @review_model INTO @report
    report = _invoke(state["review_model"], MERGE_REVIEWS_PROMPT.format(style=state["style_fb"], sec_audit=state["sec_fb"], tests=state["test_fb"]))
    print('[parallel_code_review] parallel checks complete — merging into report')
    print(f"[parallel_code_review] done | report_len={len(report)}")
    return {"report": report}

def node_commit(state: ParallelCodeReviewState) -> dict:
    # SPL: COMMIT @report
    return {}

# ── Graph  (SPL: fan-out → merge → commit) ────────────────────────────────────

def build_graph():
    g = StateGraph(ParallelCodeReviewState)
    g.add_node("parallel", node_parallel)
    g.add_node("merge",    node_merge)
    g.add_node("commit",   node_commit)

    g.set_entry_point("parallel")
    g.add_edge("parallel", "merge")
    g.add_edge("merge",    "commit")
    g.add_edge("commit",   END)
    return g.compile()

# ── Entry point  (SPL: built into CLI — `spl run ...`) ────────────────────────

@click.command()
@click.option("--code", required=True)
@click.option("--lang", default='python', show_default=True)
@click.option("--review-model", default='gemma4', show_default=True)
@click.option("--log-dir", default='cookbook/63_parallel_code_review/logs-spl', show_default=True)
def main(code: str, lang: str, review_model: str, log_dir: str):
    result = build_graph().invoke({
        "code": code,
        "lang": lang,
        "review_model": review_model,
        "log_dir": log_dir,
        "report": '',
        "sec_fb": '',
        "style_fb": '',
        "test_fb": '',
    })
    print("\n" + "=" * 60)
    print(result["report"])

if __name__ == "__main__":
    main()