```json
[
  {
    "@texts": [
      "The Transformer architecture revolutionized natural language processing by introducing self-attention mechanisms that allow models to weigh the importance of different words in a sequence dynamically.",
      "Vector databases store high-dimensional embeddings generated by machine learning models. They enable fast similarity searches using algorithms like HNSW, IVF, or exact L2 distance calculations.",
      "Retrieval-Augmented Generation combines parametric knowledge from pre-trained LLMs with non-parametric knowledge retrieved from external document stores to reduce hallucinations and improve factual accuracy."
    ],
    "@query": "How do vector databases improve the performance of similarity searches?"
  },
  {
    "@texts": [
      "Docker packages applications into standardized units called containers, which include everything needed to run the code: runtime, system tools, libraries, and settings.",
      "Kubernetes automates deploying, scaling, and managing containerized applications across clusters of hosts, providing service discovery and load balancing out of the box.",
      "CI/CD pipelines automate the integration and delivery of code changes, ensuring that software can be reliably built, tested, and deployed to production environments with minimal manual intervention."
    ],
    "@query": "What is the main advantage of using Docker for application deployment?"
  }
]
```