# S3-rag-claude_cli-sonnet.py
# Generated by splc — Python / PocketFlow target
# Source: S3-rag-claude_cli-sonnet.spl

import subprocess
import json
import re
import os
import numpy as np
from pocketflow import Node, Flow


# ---------------------------------------------------------------------------
# Utility: call Claude via claude_cli adapter
# ---------------------------------------------------------------------------

def _claude_cli(prompt: str, model: str = "sonnet") -> str:
    result = subprocess.run(
        ["claude", "-p", prompt, "--model", model],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


# ---------------------------------------------------------------------------
# SPL: CREATE FUNCTION generate_answer(query, retrieved_document)
# ---------------------------------------------------------------------------

def generate_answer(query: str, retrieved_document: str) -> str:
    prompt = (
        "You are a helpful assistant. Use the retrieved document as context "
        "to answer the user's query.\n\n"
        f"Query: {query}\n\n"
        "Retrieved Document Context:\n"
        f"{retrieved_document}\n\n"
        "Provide a clear, accurate, and comprehensive answer based solely on "
        "the context above.\n"
        "If the context doesn't contain relevant information, acknowledge this "
        "clearly rather than guessing."
    )
    return _claude_cli(prompt)


# ---------------------------------------------------------------------------
# SPL: CALL chunk_documents(@documents) INTO @texts
# ---------------------------------------------------------------------------

class ChunkDocumentsNode(Node):
    def prep(self, shared):
        return shared["documents"]

    def exec(self, documents):
        texts = []
        for doc in documents:
            # Split on double-newline; fall back to single paragraph
            chunks = [c.strip() for c in re.split(r"\n\n+", str(doc)) if c.strip()]
            texts.extend(chunks if chunks else [str(doc)])
        return texts

    def post(self, shared, prep_res, exec_res):
        # SPL: CALL chunk_documents(@documents) INTO @texts
        shared["texts"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: CALL embed_documents(@texts) INTO @embeddings
# ---------------------------------------------------------------------------

class EmbedDocumentsNode(Node):
    def prep(self, shared):
        return shared["texts"]

    def exec(self, texts):
        # Lightweight TF-IDF-style bag-of-words embedding (no external deps)
        vocab = {}
        for text in texts:
            for tok in re.findall(r"\w+", text.lower()):
                if tok not in vocab:
                    vocab[tok] = len(vocab)
        dim = max(len(vocab), 1)
        embeddings = []
        for text in texts:
            vec = np.zeros(dim)
            for tok in re.findall(r"\w+", text.lower()):
                if tok in vocab:
                    vec[vocab[tok]] += 1.0
            norm = np.linalg.norm(vec)
            embeddings.append(vec / norm if norm > 0 else vec)
        return {"embeddings": np.array(embeddings), "vocab": vocab}

    def post(self, shared, prep_res, exec_res):
        # SPL: CALL embed_documents(@texts) INTO @embeddings
        shared["embeddings"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: CALL create_faiss_index(@embeddings) INTO @index
# ---------------------------------------------------------------------------

class CreateFaissIndexNode(Node):
    def prep(self, shared):
        return shared["embeddings"]

    def exec(self, embeddings_bundle):
        # Pure-numpy nearest-neighbour index (avoids faiss dependency)
        return {"matrix": embeddings_bundle["embeddings"], "vocab": embeddings_bundle["vocab"]}

    def post(self, shared, prep_res, exec_res):
        # SPL: CALL create_faiss_index(@embeddings) INTO @index
        shared["index"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: CALL embed_query(@query) INTO @query_embedding
# ---------------------------------------------------------------------------

class EmbedQueryNode(Node):
    def prep(self, shared):
        return {"query": shared["query"], "vocab": shared["index"]["vocab"]}

    def exec(self, inp):
        query, vocab = inp["query"], inp["vocab"]
        dim = max(len(vocab), 1)
        vec = np.zeros(dim)
        for tok in re.findall(r"\w+", query.lower()):
            if tok in vocab:
                vec[vocab[tok]] += 1.0
        norm = np.linalg.norm(vec)
        return vec / norm if norm > 0 else vec

    def post(self, shared, prep_res, exec_res):
        # SPL: CALL embed_query(@query) INTO @query_embedding
        shared["query_embedding"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: CALL retrieve_document(@index, @query_embedding, @texts) INTO @retrieved_document
# ---------------------------------------------------------------------------

class RetrieveDocumentNode(Node):
    def prep(self, shared):
        return {
            "matrix": shared["index"]["matrix"],
            "query_embedding": shared["query_embedding"],
            "texts": shared["texts"],
        }

    def exec(self, inp):
        matrix = inp["matrix"]
        qvec   = inp["query_embedding"]
        texts  = inp["texts"]
        if matrix.shape[0] == 0:
            return ""
        # Cosine similarities (embeddings are already L2-normalised)
        scores = matrix @ qvec
        best_idx = int(np.argmax(scores))
        return texts[best_idx]

    def post(self, shared, prep_res, exec_res):
        # SPL: CALL retrieve_document(@index, @query_embedding, @texts) INTO @retrieved_document
        shared["retrieved_document"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: GENERATE generate_answer(@query, @retrieved_document) INTO @generated_answer
# ---------------------------------------------------------------------------

class GenerateAnswerNode(Node):
    def prep(self, shared):
        return {"query": shared["query"], "retrieved_document": shared["retrieved_document"]}

    def exec(self, inp):
        return generate_answer(inp["query"], inp["retrieved_document"])

    def post(self, shared, prep_res, exec_res):
        # SPL: GENERATE generate_answer(@query, @retrieved_document) INTO @generated_answer
        shared["generated_answer"] = exec_res
        return "default"


# ---------------------------------------------------------------------------
# SPL: EVALUATE @output_path WHEN contains(".") THEN ... ELSE ... END
# ---------------------------------------------------------------------------

class WriteOutputNode(Node):
    def prep(self, shared):
        return {
            "output_path":    shared.get("output_path", ""),
            "generated_answer": shared["generated_answer"],
        }

    def exec(self, inp):
        output_path    = inp["output_path"]
        generated_answer = inp["generated_answer"]
        # SPL: WHEN contains(".") THEN CALL write_file(@output_path, @generated_answer)
        if "." in output_path:
            os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as fh:
                fh.write(generated_answer)
            return output_path
        else:
            # SPL: ELSE @write_result := "skipped"
            return "skipped"

    def post(self, shared, prep_res, exec_res):
        shared["write_result"] = exec_res
        # SPL: RETURN @generated_answer WITH status = "complete"
        shared["status"] = "complete"
        return "default"


# ---------------------------------------------------------------------------
# WORKFLOW RAGPipeline — wire nodes into a Flow
# ---------------------------------------------------------------------------

def build_rag_pipeline() -> Flow:
    # SPL: WORKFLOW RAGPipeline
    chunk    = ChunkDocumentsNode()
    embed    = EmbedDocumentsNode()
    index    = CreateFaissIndexNode()
    embed_q  = EmbedQueryNode()
    retrieve = RetrieveDocumentNode()
    generate = GenerateAnswerNode()
    write    = WriteOutputNode()

    chunk    >> embed
    embed    >> index
    index    >> embed_q
    embed_q  >> retrieve
    retrieve >> generate
    generate >> write

    return Flow(start=chunk)


def run_rag_pipeline(
    documents: list,
    query: str,
    output_path: str = "",   # SPL: @output_path TEXT := ""
) -> str:
    """
    Entry point matching SPL WORKFLOW RAGPipeline.
    INPUT  @documents LIST, @query TEXT, @output_path TEXT := ""
    OUTPUT @generated_answer TEXT
    """
    shared = {
        "documents":   documents,
        "query":       query,
        "output_path": output_path,
    }
    flow = build_rag_pipeline()
    flow.run(shared)
    return shared["generated_answer"]   # SPL: OUTPUT @generated_answer TEXT


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    sample_documents = [
        "PocketFlow is a minimalist 100-line LLM framework for Python.",
        "SPL is a hardware-agnostic LLM orchestration language.",
        "RAG stands for Retrieval-Augmented Generation.",
        "FAISS is a library for efficient similarity search.",
        "Claude is an AI assistant made by Anthropic.",
    ]
    sample_query = sys.argv[1] if len(sys.argv) > 1 else "What is PocketFlow?"
    out_path     = sys.argv[2] if len(sys.argv) > 2 else ""

    answer = run_rag_pipeline(sample_documents, sample_query, out_path)
    print("\n=== Generated Answer ===")
    print(answer)