"""
pocketflow_agent — generated by splc (deterministic Python/PocketFlow transpiler)

PocketFlow pattern: prep(shared) → exec(prep_res) → post(shared, prep_res, exec_res)
                    Extract       → Transform        → Load
                    (ETL applied to LLM orchestration)

Pattern: draft → critique → ([APPROVED]? commit : refine → critique)

Usage:
    pip install pocketflow click
    python pocketflow_agent_python_pocketflow.py --task "Your task here"
"""

from pathlib import Path

import click
from pocketflow import Flow, Node

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

DECIDEACTION_PROMPT = """\
Given the query: {query} and the current context: {context}, decide whether to 'search' for more information or 'answer' the question.
If searching, provide a concise search query. If answering, provide the answer.
Output format:
If you need to search: search: [your search query]
If you are ready to answer: answer: [your final answer]"""

ANSWERQUESTION_PROMPT = """\
Given the original query: {query} and the gathered information: {context}, provide a comprehensive answer."""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _call_llm(model: str, prompt: str) -> str:
    """Call the LLM via Ollama REST API. Replace with your preferred adapter."""
    import urllib.request, json
    payload = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["response"].strip()


def _write(path: str, content: str) -> None:
    """Write content to a file, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ── Nodes  (each mirrors one GENERATE / EVALUATE block) ──────────────────────

class DraftNode(Node):
    # SPL: initial draft

    def prep(self, shared):
        # Extract — pull INPUT vars from shared store
        initial_query = shared["initial_query"]
        return initial_query

    def exec(self, prep_res):
        # Transform — LLM call
        return ""

    def post(self, shared, prep_res, exec_res):
        # Load — write results back to shared store
        shared["current"] = exec_res
        shared["iteration"] = 0
        return "critique"

class CritiqueNode(Node):
    # SPL: GENERATE critique(@current) INTO @action
    # post() mirrors EVALUATE @action WHEN contains("answer:") + WHILE guard

    def prep(self, shared):
        # Extract — pull current draft, iteration counter, and model
        return shared["current"], shared.get("iteration", 0)

    def exec(self, prep_res):
        # Transform — LLM critique call
        current, _ = prep_res
        print("Critiquing current draft ...")
        return _call_llm("llama3.2", DECIDEACTION_PROMPT.format(query=current, context=""))

    def post(self, shared, prep_res, exec_res):
        # Load — save feedback; route based on EVALUATE + WHILE guard
        shared["action"] = exec_res
        _, i = prep_res
        if 'answer:' in exec_res:
            print(f"Approved at iteration {i}")
            return "commit"
        if i >= shared.get("max_iterations", 3):
            print(f"Max iterations reached | iterations={i}")
            return "commit"
        return "refine"

class RefineNode(Node):
    # SPL: GENERATE refine(@current, @feedback) INTO @current

    def prep(self, shared):
        # Extract — pull current draft, feedback, iteration counter, and model
        return shared["current"], shared["feedback"], shared.get("iteration", 0)

    def exec(self, prep_res):
        # Transform — LLM refinement call
        current, feedback, _ = prep_res
        return current

    def post(self, shared, prep_res, exec_res):
        # Load — update draft and increment iteration counter
        shared["current"] = exec_res
        shared["iteration"] = prep_res[2] + 1
        return "critique"

class CommitNode(Node):
    # SPL: RETURN @current WITH status, iterations

    def prep(self, shared):
        return shared.get("current", ""), shared.get("iteration", 0), shared.get("feedback", "")

    def exec(self, prep_res):
        return prep_res

    def post(self, shared, prep_res, exec_res):
        # Load — write final output and log status
        current, i, feedback = exec_res
        approved = shared.get("feedback", "") and "[APPROVED]" in shared.get("feedback", "")
        status = "complete" if approved else "max_iterations"
        print(f"\nStatus:     {status}")
        print(f"Iterations: {i}")
        print(f"\n{current}")
        shared["status"] = status
        return None

# ── Flow wiring  (mirrors WORKFLOW control flow) ─────────────────────────────
# SPL:  draft → WHILE loop → EVALUATE → commit or refine → critique
#
# PocketFlow conditional edges via post() return value (action string):
#   critique.post() → "commit"  (EVALUATE [APPROVED] or max_iterations)
#   critique.post() → "refine"  (else branch)
#   refine.post()   → "critique" (loop back)
#   draft.post()    → "critique" (initial transition)

def build_flow() -> Flow:
    draft   = DraftNode()
    critique = CritiqueNode()
    refine  = RefineNode()
    commit  = CommitNode()

    # SPL: initial draft → critique
    draft   - "critique" >> critique

    # SPL: EVALUATE + WHILE guard → commit or refine
    critique - "commit"  >> commit
    critique - "refine"  >> refine

    # SPL: WHILE back-edge — refine → critique
    refine  - "critique" >> critique

    return Flow(start=draft)

# ── Entry point  (SPL: built into CLI — `spl3 run ...`) ────────────────────────

@click.command()
@click.option("--initial-query", required=True)
def main(initial_query: str):
    # SPL: INPUT @vars → shared store (ETL staging area)
    shared = {
        "initial_query": initial_query,
        "iteration": 0,
        "current": "",
        "feedback": "",
    }
    build_flow().run(shared)


if __name__ == "__main__":
    main()