"""
react_research — generated by splc (deterministic Python/PocketFlow transpiler)

PocketFlow pattern: prep(shared) → exec(prep_res) → post(shared, prep_res, exec_res)
                    Extract       → Transform        → Load
                    (ETL applied to LLM orchestration)

Pattern: decide → ([action: answer]? answer : search → update_context → decide)

Usage:
    pip install pocketflow click
    python react_research_python_pocketflow.py --task "Your task here"
"""

from pathlib import Path

import click
from pocketflow import Flow, Node

# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) ──────────────────────────

DECIDEACTION_PROMPT = """\
  You are a research assistant. Analyze whether you can answer the question with current information.

  Question: {question}

  Research context so far:
  {context}

  Think step-by-step:
  1. What specific information does this question require?
  2. What relevant information do you currently have?
  3. What critical gaps remain that prevent a complete answer?
  4. Can you provide a comprehensive, accurate response now?

  Output your decision in this YAML format:

  reasoning: "Your detailed step-by-step analysis"
  action: search
  search_query: "specific search terms for missing information"

  Use action "search" if significant information gaps remain.
  Use action "answer" if you have sufficient context for a complete response.

  IMPORTANT: Ensure valid YAML formatting. If syntax errors occur, immediately provide a corrected version."""

ANSWERQUESTION_PROMPT = """\
  Synthesize a comprehensive answer using all gathered research.

  Original question: {question}

  Complete research context:
  {context}

  Provide a thorough, well-structured response that directly addresses the question.
  Reference key findings and sources from your research."""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _call_llm(model: str, prompt: str) -> str:
    """Call the LLM via Ollama REST API. Replace with your preferred adapter."""
    import urllib.request, json
    payload = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["response"].strip()


def _write(path: str, content: str) -> None:
    """Write content to a file, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def _web_search(query: str, max_results: int = 5) -> str:
    """Search the web via DuckDuckGo — auto-extracts search_query from YAML."""
    import re
    try:
        from ddgs import DDGS
    except ImportError:
        from duckduckgo_search import DDGS
    m = re.search(r'search_query:\s*(.+)', query)
    if m:
        query = m.group(1).strip().strip('"').strip("'")
    try:
        results = DDGS().text(query.strip(), max_results=max_results)
        if not results:
            return f"No results for: {query}"
        lines = []
        for i, r in enumerate(results, 1):
            title = r.get("title", "")
            url   = r.get("href", "")
            body  = r.get("body", "")
            lines.append(f"[{i}] {title}\n    URL: {url}\n    {body}")
        return "\n\n".join(lines)
    except Exception as e:
        return f"Search error: {e}"

# ── Nodes  (each mirrors one GENERATE / CALL / EVALUATE block) ────────────────

class DecideNode(Node):
    # SPL: GENERATE DecideAction(...) INTO @decision
    # post() routes: 'action: answer|action: "answer"' → answer; else → search

    def prep(self, shared):
        # Extract — inputs + accumulated context
        question = shared["question"]
        max_iterations = shared["max_iterations"]
        context = shared.get("context", "")
        return question, max_iterations, context

    def exec(self, prep_res):
        # Transform — LLM decides: search or answer
        question, max_iterations, context = prep_res
        print("Deciding next action ...")
        return _call_llm("llama3.2", DECIDEACTION_PROMPT.format(question=question, context=max_iterations))

    def post(self, shared, prep_res, exec_res):
        # Load — store decision; EVALUATE routing
        shared["decision"] = exec_res
        i = shared.get("iteration", 0)
        if 'action: answer|action: "answer"' in exec_res:
            return "answer"
        if i >= shared.get("max_iterations", 3):
            return "answer"
        return "search"

class SearchNode(Node):
    # SPL: CALL web_search(@decision) INTO @search_results + context update

    def prep(self, shared):
        # Extract — decision YAML and current context
        return shared.get("decision", ""), shared.get("context", "")

    def exec(self, prep_res):
        # Transform — web search (extracts search_query from YAML automatically)
        decision, _ = prep_res
        print("Searching the web ...")
        return _web_search(decision)

    def post(self, shared, prep_res, exec_res):
        # Load — store results; update context and iteration counter
        _, context = prep_res
        shared["search_results"] = exec_res
        shared["context"] = shared["context"] + '\n\n--- Search Results ---\n' + shared["search_results"]
        shared["iteration"] = shared["iteration"] + 1
        return "decide"

class AnswerNode(Node):
    # SPL: GENERATE AnswerQuestion(...) INTO @answer + RETURN

    def prep(self, shared):
        # Extract — original question and full research context
        question = shared["question"]
        max_iterations = shared["max_iterations"]
        context = shared.get("context", "")
        return question, max_iterations, context

    def exec(self, prep_res):
        # Transform — synthesize final answer from all gathered research
        question, max_iterations, context = prep_res
        print("Generating final answer ...")
        return _call_llm("llama3.2", ANSWERQUESTION_PROMPT.format(question=question, context=max_iterations))

    def post(self, shared, prep_res, exec_res):
        # Load — write answer and print status
        shared["answer"] = exec_res
        i = shared.get("iteration", 0)
        max_i = shared.get("max_iterations", 3)
        status = "complete" if i < max_i else "max_iterations"
        print(f"\nStatus:     {status}")
        print(f"Iterations: {i}")
        print(f"\n{exec_res}")
        shared["status"] = status
        return None

# ── Flow wiring  (mirrors WORKFLOW control flow) ─────────────────────────────
# SPL:  WHILE loop → GENERATE DecideAction → EVALUATE → answer or search
#
# PocketFlow conditional edges via post() return value (action string):
#   decide.post() → "answer"  (EVALUATE contains match OR max_iterations guard)
#   decide.post() → "search"  (else branch — external tool call needed)
#   search.post() → "decide"  (WHILE back-edge — loop continues)

def build_flow() -> Flow:
    decide = DecideNode()
    search = SearchNode()
    answer = AnswerNode()

    # SPL: EVALUATE exit condition → answer
    decide - "answer" >> answer

    # SPL: ELSE branch → search tool call
    decide - "search" >> search

    # SPL: WHILE back-edge — search → decide
    search - "decide" >> decide

    return Flow(start=decide)

# ── Entry point  (SPL: built into CLI — `spl3 run ...`) ────────────────────────

@click.command()
@click.option("--question", required=True)
@click.option("--max-iterations", default=3, show_default=True, type=int)
def main(question: str, max_iterations: int):
    # SPL: INPUT @vars → shared store (ETL staging area)
    shared = {
        "question": question,
        "max_iterations": max_iterations,
        "context": 'Initial question: ' + question,
        "iteration": 0,
        "decision": "",
        "search_results": "",
        "answer": "",
    }
    build_flow().run(shared)


if __name__ == "__main__":
    main()