#!/usr/bin/env python3
"""
parallel_code_review.py
Generated by splc — CrewAI target
Source: parallel_code_review.spl (Recipe 63: Parallel Code Review)
"""

import argparse
import logging
import os
import sys

from crewai import Agent, Crew, LLM, Process, Task

# ---------------------------------------------------------------------------
# Logging  (SPL: LOGGING ... LEVEL INFO / ERROR / WARN)
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("parallel_code_review")


# ---------------------------------------------------------------------------
# LLM factory
# ---------------------------------------------------------------------------

def _make_llm(review_model: str, max_tokens: int | None = None) -> LLM:
    base_url = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
    kwargs: dict = dict(
        model=f"ollama/{review_model}",
        base_url=base_url,
        temperature=0.3,
    )
    if max_tokens is not None:
        kwargs["max_tokens"] = max_tokens
    return LLM(**kwargs)


# ---------------------------------------------------------------------------
# IMPORT '00_style_review'
# ---------------------------------------------------------------------------

def _build_style_review(llm: LLM, code: str, lang: str) -> tuple[Agent, Task]:
    # SPL: IMPORT '00_style_review'
    agent = Agent(
        role="Style & Correctness Reviewer",
        goal=(
            "Review source code for style issues, naming conventions, readability, "
            "and logical correctness; identify bugs and code smells."
        ),
        backstory=(
            f"Senior software engineer specialising in {lang} style guides "
            "(PEP 8, clean-code principles). Rates every finding CRITICAL / MODERATE / LOW."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
    )
    # SPL: CALL style_review(@code, lang=@lang, review_model=@review_model, ...) INTO @style_fb
    task = Task(
        description=(
            f"Perform a thorough style and correctness review of this {lang} code.\n\n"
            f"```{lang}\n{code}\n```\n\n"
            "Report naming, formatting, readability issues, logic bugs, and code smells. "
            "Rate each finding CRITICAL, MODERATE, or LOW."
        ),
        expected_output=(
            "Structured style-and-correctness review with every finding rated "
            "CRITICAL / MODERATE / LOW."
        ),
        agent=agent,
        async_execution=True,   # SPL: CALL PARALLEL branch 1
    )
    return agent, task


# ---------------------------------------------------------------------------
# IMPORT '01_security_audit'
# ---------------------------------------------------------------------------

def _build_security_audit(llm: LLM, code: str, lang: str) -> tuple[Agent, Task]:
    # SPL: IMPORT '01_security_audit'
    agent = Agent(
        role="Security Auditor",
        goal=(
            "Identify security vulnerabilities, injection risks, insecure dependencies, "
            "and dangerous patterns in source code."
        ),
        backstory=(
            "Application security expert with deep knowledge of OWASP Top 10 and CWE "
            "classifications. Rates every finding CRITICAL / MODERATE / LOW."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
    )
    # SPL: CALL security_audit(@code, lang=@lang, review_model=@review_model, ...) INTO @sec_fb
    task = Task(
        description=(
            f"Perform a comprehensive security audit of this {lang} code.\n\n"
            f"```{lang}\n{code}\n```\n\n"
            "Identify injection vulnerabilities, insecure patterns, data-exposure risks, "
            "and dependency issues. Rate each finding CRITICAL, MODERATE, or LOW."
        ),
        expected_output=(
            "Structured security-audit report with every finding rated "
            "CRITICAL / MODERATE / LOW."
        ),
        agent=agent,
        async_execution=True,   # SPL: CALL PARALLEL branch 2
    )
    return agent, task


# ---------------------------------------------------------------------------
# IMPORT '02_test_generator'
# ---------------------------------------------------------------------------

def _build_test_generator(llm: LLM, code: str, lang: str) -> tuple[Agent, Task]:
    # SPL: IMPORT '02_test_generator'
    agent = Agent(
        role="Test Case Generator",
        goal=(
            "Generate comprehensive, executable unit tests covering happy paths, "
            "edge cases, and failure modes for the given code."
        ),
        backstory=(
            f"QA engineer who writes thorough pytest suites for {lang} projects; "
            "focuses on coverage, edge cases, and meaningful assertions."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
    )
    # SPL: CALL test_generator(@code, lang=@lang, review_model=@review_model, ...) INTO @test_fb
    task = Task(
        description=(
            f"Generate a complete test suite for this {lang} code.\n\n"
            f"```{lang}\n{code}\n```\n\n"
            "Include unit tests for all public functions, edge-case tests, "
            "and at least one failure-mode test. Use pytest conventions."
        ),
        expected_output=(
            "Complete pytest test suite in a fenced code block, ready to run without modification."
        ),
        agent=agent,
        async_execution=True,   # SPL: CALL PARALLEL branch 3
    )
    return agent, task


# ---------------------------------------------------------------------------
# CREATE FUNCTION merge_reviews(style TEXT, sec_audit TEXT, tests TEXT) RETURN TEXT
# ---------------------------------------------------------------------------

def _build_merge(
    llm: LLM,
    style_task: Task,
    security_task: Task,
    test_task: Task,
) -> tuple[Agent, Task]:
    # SPL: CREATE FUNCTION merge_reviews(style TEXT, sec_audit TEXT, tests TEXT) RETURN TEXT AS $$...$$
    agent = Agent(
        role="Engineering Lead — Code Review Consolidator",
        goal=(
            "Synthesise style, security, and test-coverage findings from the three parallel "
            "reviews into one prioritised, actionable engineering report."
        ),
        backstory=(
            "Principal engineer who has reviewed thousands of PRs; cuts through noise, "
            "prioritises ruthlessly (CRITICAL before MODERATE before LOW), "
            "and communicates with clarity."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
    )
    # SPL: GENERATE merge_reviews(@style_fb, @sec_fb, @test_fb)
    #      WITH OUTPUT BUDGET 1024 TOKENS
    #      USING MODEL @review_model
    #      INTO @report
    task = Task(
        description=(
            "You have received three independent code-review reports as context "
            "(style review, security audit, test cases).\n\n"
            "Consolidate them into a single report with exactly these sections:\n\n"
            "1. **Action Items** — numbered list of changes, CRITICAL first, "
            "then MODERATE, then LOW (≤ 150 words total)\n"
            "2. **Test Coverage** — paste the generated tests verbatim in a fenced code block\n"
            "3. **Summary** — one paragraph overall assessment: "
            "is this code production-ready?\n\n"
            "Draw all content from the context tasks; do not invent findings."
        ),
        expected_output=(
            "Consolidated engineering report with three sections: "
            "Action Items (≤ 150 words), Test Coverage (code block), Summary (one paragraph)."
        ),
        agent=agent,
        context=[style_task, security_task, test_task],   # SPL: fan-in after CALL PARALLEL END
    )
    return agent, task


# ---------------------------------------------------------------------------
# WORKFLOW parallel_code_review
# ---------------------------------------------------------------------------

def parallel_code_review(
    code: str,
    lang: str = "python",                                          # SPL: @lang    TEXT DEFAULT 'python'
    review_model: str = "gemma4",                                  # SPL: @review_model TEXT DEFAULT 'gemma4'
    log_dir: str = "cookbook/63_parallel_code_review/logs-spl",   # SPL: @log_dir  TEXT DEFAULT '...'
) -> str:
    """Fan-out three concurrent LLM reviews, then merge into a prioritised report.

    Returns the consolidated review report string (SPL OUTPUT: @report TEXT).
    """

    # SPL: LOGGING f'[parallel_code_review] starting 3-way parallel review ...' LEVEL INFO
    logger.info(
        "[parallel_code_review] starting 3-way parallel review | lang=%s review_model=%s",
        lang,
        review_model,
    )

    os.makedirs(log_dir, exist_ok=True)

    report: str = ""

    try:
        llm = _make_llm(review_model)
        # Separate LLM instance for the merge step enforces the 1024-token output budget.
        merge_llm = _make_llm(review_model, max_tokens=1024)

        # SPL: CALL PARALLEL
        #        style_review   (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @style_fb,
        #        security_audit (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @sec_fb,
        #        test_generator (@code, lang=@lang, review_model=@review_model, log_dir=@log_dir) INTO @test_fb
        #      END
        _, style_task    = _build_style_review(llm, code, lang)
        _, security_task = _build_security_audit(llm, code, lang)
        _, test_task     = _build_test_generator(llm, code, lang)

        # SPL: GENERATE merge_reviews(@style_fb, @sec_fb, @test_fb)
        #      WITH OUTPUT BUDGET 1024 TOKENS USING MODEL @review_model INTO @report
        _, merge_task = _build_merge(merge_llm, style_task, security_task, test_task)

        crew = Crew(
            agents=[
                style_task.agent,
                security_task.agent,
                test_task.agent,
                merge_task.agent,
            ],
            tasks=[style_task, security_task, test_task, merge_task],
            # Process.sequential with async_execution=True on the first three tasks causes
            # CrewAI to run those three concurrently, then gate the merge task on all three.
            process=Process.sequential,
            verbose=False,
        )

        crew_output = crew.kickoff()

        # SPL: LOGGING '[parallel_code_review] parallel checks complete — merging into report' LEVEL INFO
        logger.info("[parallel_code_review] parallel checks complete — merging into report")

        report = crew_output.raw if hasattr(crew_output, "raw") else str(crew_output)

        # SPL: LOGGING f'[parallel_code_review] done | report_len={len(@report)}' LEVEL INFO
        logger.info("[parallel_code_review] done | report_len=%d", len(report))

        # SPL: COMMIT @report
        return report

    except (ConnectionError, OSError) as exc:
        # SPL: EXCEPTION WHEN ModelUnavailable THEN
        #        LOGGING f'[parallel_code_review] model unavailable: {@review_model}' LEVEL ERROR
        #        RETURN '[ERROR] Model unavailable.' WITH status = 'failed'
        logger.error(
            "[parallel_code_review] model unavailable: %s — %s",
            review_model,
            exc,
        )
        return "[ERROR] Model unavailable."

    except Exception as exc:  # noqa: BLE001
        msg = str(exc).lower()
        if any(kw in msg for kw in ("budget", "token", "context length", "max_tokens", "too long")):
            # SPL: EXCEPTION WHEN BudgetExceeded THEN
            #        LOGGING '[parallel_code_review] token budget exceeded during merge' LEVEL WARN
            #        COMMIT @report WITH status = 'truncated'
            logger.warning(
                "[parallel_code_review] token budget exceeded during merge: %s", exc
            )
            # Return whatever partial output was captured before the budget error.
            return report or "[TRUNCATED] Token budget exceeded — partial report unavailable."

        raise


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="parallel_code_review",
        description="Recipe 63 — Parallel Code Review compiled from SPL to CrewAI",
    )
    source = p.add_mutually_exclusive_group(required=True)
    source.add_argument("--code", help="Inline source code snippet to review")
    source.add_argument(
        "--file", dest="code_file", metavar="PATH",
        help="Path to a source file to review",
    )
    p.add_argument("--lang", default="python", help="Programming language (default: python)")
    p.add_argument(
        "--review-model", default="gemma4", dest="review_model",
        help="Ollama model name (default: gemma4)",
    )
    p.add_argument(
        "--log-dir", default="cookbook/63_parallel_code_review/logs-spl", dest="log_dir",
        help="Directory for log output",
    )
    return p


if __name__ == "__main__":
    args = _build_arg_parser().parse_args()

    if args.code_file:
        with open(args.code_file) as fh:
            code_input = fh.read()
    else:
        code_input = args.code

    report_output = parallel_code_review(
        code=code_input,
        lang=args.lang,
        review_model=args.review_model,
        log_dir=args.log_dir,
    )

    print("\n" + "=" * 72)
    print("CONSOLIDATED CODE REVIEW REPORT")
    print("=" * 72 + "\n")
    print(report_output)